### PR TITLE
ENT-5069 - vault query fix for notary health check

### PR DESCRIPTION
**Pull request by nikinagy**
As discussed before we also want to have this change in OS 4.6.

Handling the empty list of uuids.
https://r3-cev.atlassian.net/browse/ENT-5069

### CODE REVIEW

**Review by mnesbit — DISMISSED** [review]
ok

**Review by mnesbit — COMMENTED** [review]
Actually I spot other places where we can pass emptyList to an `in` clause. Can we fix those too, or throw error if they make no sense in context

**Comment by rick-r3** [comment]
Are we still re-thinking what should happen here?  Or is this the re-thought version?

**Comment by nikinagy** [comment]
I am currently working on the new version

**Comment by mnesbit** [comment]
This is the version that returns all linear states on an empty list. When it would be more consistent to return zero records as there are no matches.

**Pull request closed without merging**
