### PR TITLE
add smoke tests via comment trigger build

### PR DESCRIPTION
**Pull request by roastario**

### CODE REVIEW

**Comment by roastario** [comment]
run smoke tests please

**Comment by roastario** [comment]
run smoke tests again

**Comment by roastario** [comment]
run smoke tests !!!

**Comment by roastario** [comment]
run smoke tests again

**Comment by roastario** [comment]
ok this time reaaaaaallly run smoke tests please

**Comment by roastario** [comment]
Run smoke tests again

**Review by Schife — APPROVED** [review]
LGTM

**Pull request merged**
