### PR TITLE
ENT-1887 Make sure open and enterprise API are identical

### PR DESCRIPTION
**Pull request by josecoll**
A minimal number of API discrepancies (2x additional constructor params, one additional function) were identified.

Andras will remove a couple of SGX specific public api's from Enterprise (eg. _SgxSupport_, _DummySecureRandom_ in _CryptoUtils_).

The only true difference between OS and Enterprise is the additional _Liquibase_ related field `protected open val migrationResource: String? = null` in `MappedSchema`.
This will be back-ported to OS as and when we back-port _Liquibase_ support.
It should also be noted that the Liquibase `DBScriptRunner` tool is also in ENT only (for now)

### CODE REVIEW

**Comment by josecoll** [comment]
@szymonsztuka please review the database specific changes (eg. MockServices synchronisation required additional helper methods not in OS)

**Comment by josecoll** [comment]
@tudor please review the sync-up of `Driver` related discrepancies.

**Comment by tudor-malene** [comment]
Wrt the ``protected migrationResource`` field on the ``MappedSchema``. 

Here's how it works:

- If you are writing a CorDapp against OS, you don't know about it. 
- If you take the binaries of that CorDapp and run them against ENT, then the "migrationResource" is not overridden, and defaults to null. ( which means no migration is set for that MappedSchema )
- If you write the CorDapp against ENT and actually override the field, then if you run the CorDapp on OS, the core will just ignore that field .
- If you take the OS CorDapp and compile it against ENT, it should work fine, as the fields defaults to null
- The only thing that you can't do, is try to compile an ENT CorDapp with the override against OS

( This is the original PR: https://github.com/corda/enterprise/pull/150)

**Comment by josecoll** [comment]
Thanks @tudor-malene.
That is a great description - is it included in the official docs? (if not, please add it)

**Pull request merged**
