### PR TITLE
CORDA-2333: Dependency update pass for tests and demos

### PR DESCRIPTION
**Pull request by shamsasari**

### CODE REVIEW

**Comment by mikehearn** [comment]
Nice! Can we get Kotlin 1.3 as well?

**Comment by shamsasari** [comment]
Will do that as a separate PR.

**Comment by josecoll** [comment]
Looks good to me - let me test this commit against my JDK11 feature branch (make sure nothing drastically breaks).

**Comment by josecoll** [comment]
No negative impact on JDK11 build (https://ci-master.corda.r3cev.com/viewLog.html?buildId=181638&buildTypeId=Corda_Build_Jdk11_BuildOpenJDK11Patched)

**Pull request merged**
