### PR TITLE
TM-168 reusable configurations for distributed testing

### PR DESCRIPTION
**Pull request by Schife**
Introducing reusable configurations to enable easier maintenance

### CODE REVIEW

**Comment by Schife** [comment]
run tests: slow

**Comment by Schife** [comment]
run tests: slow

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Review by relyafi — CHANGES_REQUESTED** [review]
This is a step in the right direction, but ideally, we'd be able to reduce this to a single line in each task, as in, specify a profile rather than taking shared variables for each attribute. To that end:

1) Is it possible that we can just reference the profile name, e.g. resourceProfile generalPurpose, then get the plugin to parse the associated list?
2) Can we make it more obvious that these are resource profile configurations, e.g. putting them in a separate gradle file? Longer term that might let us include resource profiles from a centralised project as well.

**Comment by Schife** [comment]
I'll answer each point
1. In the current implementation of the plugin no we cannot. We can maybe create a profile object that can get passed into the ParallelTestGroup but after some searching I've not found an easy way to instantiate an object of a specific type within gradle
2. We can place all of the values into a profile.properties file and then load it via : 
`Properties generalPurpose= new Properties()
 file("$projectDir/generalPurpose.properties").withInputStream { generalPurpose.load(it) }`

but then you would still have to load all the values into an ext object
`ext.generalPurpose.numberOfShards = generalPurpose.getProperty("numberOfShards")`

Even with this, the end assignment will still look the same, albeit more convoluted and harder to understand

**Pull request merged**
