### PR TITLE
Master

### PR DESCRIPTION
**Pull request by cyrsis**
Make Gradle build Time from 4 mins to 2 mins

### CODE REVIEW

**Comment by Clintonio** [comment]
Seems to be failing in CI. Will run again before I defer back to you.

**Comment by cyrsis** [comment]
Thanks

**Comment by Clintonio** [comment]
So it looks the parallel option is causing the integration tests to run in parallel. Those currently all bind to the same port range (10000-10020). If you have time to fix this there are a few options I can see;

1) disable parallel for integration tests
2) change the integration test drivers to start at different port numbers
3) change the integration test drivrs to use random/free ports

1 I am not sure is possible. 2 is most likely to work (but may cause the tests to fail due to memory issues or timeouts instead). 3 is similar to 2 but worse since it'll incur even more spurious errors since we tried that strategy before.

There may be other strategies, but if you want to test your changes you can run `./gradlew integrationTest` to catch these issues.

And just to add again; thanks for the effort you've put in so far 👍

**Comment by cyrsis** [comment]
Sure, will do, need to speed up this thing for a bit

**Pull request closed without merging**
