### PR TITLE
Change IOU Example docs

### PR DESCRIPTION
**Pull request by Procelius**
Continuation of [#162](https://github.com/corda/cordapp-example/pull/162)

# PR Checklist:

- [X] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [X] If you added public APIs, did you write the JavaDocs?
- [X] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [X] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Thanks for your code, it's appreciated! :)

### CODE REVIEW

**Comment by anthonykeenan** [comment]
@vkolomeyko @Procelius 

I don't understand this PR??

https://github.com/corda/cordapp-example/blob/release-V4/kotlin-source/build.gradle#L96

The webport has been changed to 10009 on both the release-V3 and release-V4 branches - why have we changed the port back to the old one?

**Comment by vkolomeyko** [comment]
I think what is happening is that it is possible to start nodes with  IOU Example CorDapp using two distinct methods:
1. Using `deployNodes` target this is when passed `webPort` does have effect;
2. Using IntelliJ run configuration and this is when `webPort` and other ports cannot be specified and we rely on the PortAllocation.

This PR is changing instructions w.r.t. IntelliJ run configurations for which port allocation recently changed.

@Procelius - could you confirm my understanding is correct?

**Comment by anthonykeenan** [comment]
I think if that's the case, the `example-cordapp` needs changing so that the ports are the same for both `deployNodes` and via IntelliJ, otherwise it's just confusing.

**Comment by Procelius** [comment]
@vkolomeyko, Ok, I'm on it.

**Pull request merged**
