### PR TITLE
CORDA-1123 Node explorer / Demobench UI issues

### PR DESCRIPTION
**Pull request by patrickkuo**

### CODE REVIEW

**Comment by patrickkuo** [comment]
https://r3-cev.atlassian.net/browse/CORDA-1123

**Comment by kchalkias** [comment]
It works on Windows as well.
image

**Comment by kchalkias** [comment]
this PR solves one of the UI issues of CORDA-1123.

**Comment by kchalkias** [comment]
As for the 2nd UI issue tooltip works in windows as well - didn't notice there was a tooltip, as it appears after stopping my pointer for ~2secs, but it does the job.

**Pull request merged**
