### PR TITLE
CORDA-943 - Deterministic serialization order breaks object ref cache

### PR DESCRIPTION
**Pull request by fenryka**
Backport from master - https://github.com/corda/corda/pull/2440

### CODE REVIEW

**Comment by fenryka** [comment]
@josecoll can you OK this review, it's a backport into the release from master, linked PR is above

**Comment by josecoll** [comment]
@GavT over to you for approval of this.
How do we intend to regression test this fix?

**Comment by josecoll** [comment]
@fenryka just realised, this PR needs to be raised against Enterprise repo `release-V3-DEV-PREVIEW` branch if it really needs to be released at all.

**Comment by fenryka** [comment]
@josecoll It'll go into DP 4 after 9th Feb

**Pull request merged**
