### PR TITLE
ENT-5532 Terminate sessions after original io request

### PR DESCRIPTION
**Pull request by lankydan**
Sessions are now terminated after performing the original
`FlowIORequest` passed into `StartedFlowTransition`, instead of before.
This is done by scheduling an `Event.TerminateSessions` if there are
sessions to terminate when performing a suspending event.

Originally this was done by hijacking a transition that is trying to
perform a `StartedFlowTransition`, terminating the sessions and then
scheduling another `Event.DoRemainingWork` to perform the original
transition. This introduced a bug where, another event (from a external
message) could be placed onto the queue before the
`Event.DoRemainingWork` could be added. In most scenarios, that should
be ok. But, if a flow is retrying (while in an uninitiated state) and
this occurs the flow could fail due to being in an unexpected state.

Terminating the sessions after performing the original transition
removes this possibility. Meaning that a restarting flow will always
perform the transition they supposed to do (based on the called
suspending event).

### CODE REVIEW

**Comment by lankydan** [comment]
Run tests: slow

**Review by rick-r3 — DISMISSED** [review]
Seems okay to me.  What does @dimosr think ?

**Review by dimosr — DISMISSED** [review]
Yes, looks good to me too.

**Review by rick-r3 — APPROVED** [review]
LGTM, but I've already seen this :-)  @dimosr can maybe provide independent review

**Review by dimosr — APPROVED** [review]
LGTM

**Pull request merged**
