### PR TITLE
CORDA-2803: Add default timeouts for the http connections

### PR DESCRIPTION
**Pull request by tudor-malene**
see https://r3-cev.atlassian.net/browse/ENT-3373

### CODE REVIEW

**Comment by shamsasari** [comment]
With the timeout in place does it fix the issue, or it expose the underlying issue?

**Comment by tudor-malene** [comment]
> With the timeout in place does it fix the issue, or it expose the underlying issue?

With the timeout in place, the http connection will throw a `SocketException` in 30sec. 
This will be caught by the `NetworkMapUpdater.watchHttpNetworkMap` or `subscribeToNetworkMap` as it was called before which will just retry.

I haven't tried this myself, but it seems fairly straight forward. 
Do you think this deserves a test?
It looks like fairly standard behaviour to me.

**Comment by shamsasari** [comment]
I meant, does this fix the original testnet issue?

**Comment by tudor-malene** [comment]
> I meant, does this fix the original testnet issue?

From the jstack posted by @Clintonio , yes

``` - sun.net.www.protocol.http.HttpURLConnection.getInputStream() @bci=52, line=1492 (Compiled frame)
 - java.net.HttpURLConnection.getResponseCode() @bci=16, line=480 (Compiled frame)
 - sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode() @bci=4, line=347 (Compiled frame)
 - net.corda.core.internal.InternalUtils.checkOkResponse(java.net.HttpURLConnection) @bci=7, line=432 (Compiled frame)
 - net.corda.node.services.network.NetworkMapClient.getNetworkMap(java.util.UUID) @bci=113, line=113 (Compiled frame)
 - net.corda.node.services.network.NetworkMapClient.getNetworkMap$default(net.corda.node.services.network.NetworkMapClient, java.util.UUID, int, java.lang.Object) @bci=13, line=62 (Compiled frame)
 - net.corda.node.services.network.NetworkMapUpdater.updateNetworkMapCache(net.corda.node.services.network.NetworkMapClient) @bci=4, line=109 (Compiled frame)
 - net.corda.node.services.network.NetworkMapUpdater.access$updateNetworkMapCache(net.corda.node.services.network.NetworkMapUpdater, net.corda.node.services.network.NetworkMapClient) @bci=2, line=44 (Compiled frame)
 - net.corda.node.services.network.NetworkMapUpdater$subscribeToNetworkMap$3.run() @bci=12, line=97 (Compiled frame)
 - java.util.concurrent.Executors$RunnableAdapter.call() @bci=4, line=511 (Compiled frame)
```

**Pull request merged**
