### PR TITLE
CORDA-1191 SMM bugs

### PR DESCRIPTION
**Pull request by exFalso**
This PR includes fixes for bugs found as part of CORDA-1191

### CODE REVIEW

**Comment by mikehearn** [comment]
Can we get this merged?

**Comment by tudor-malene** [comment]
@mikehearn 
I tested it, and found other issues that I mentioned on the ticket.
It's actually a bit worse than before.

**Comment by exFalso** [comment]
@mikehearn I'd like to fix all issues relating to CORDA-1191 here, especially if the fixes are making the issues more prevalent

**Comment by tlil** [comment]
@exFalso how's the work on this going? I saw you added `HardRestartTest` - if CI pass, is this one good to go?

**Comment by exFalso** [comment]
@tlil this is good to go once i rebase

**Pull request merged**
