### PR TITLE
[EG-1404] Retired the rst doc source structure under /docs and update…

### PR DESCRIPTION
**Pull request by ivanterziev-r3**
EG-1404 Retired the rst doc source structure under /docs and updated the /docs/README.md

I have read the contributor agreement and my PR is in accordance with the Developer's Certificate of Origin.

### CODE REVIEW

**Comment by ivanterziev-r3** [comment]
@barrylapthorn @wzur-r3  Who else needs to review this PR?

NB this will impact any other open PRs that have commits to `/docs/...` files.

**Review by wzur-r3 — DISMISSED** [review]
LGTM

**Comment by ivanterziev-r3** [comment]
Can someone with merge powers please action this?

**Comment by ivanterziev-r3** [comment]
It seems that some of the sub-dirs in /docs might need to be kept e.g. `/whitepaper` and `/example-code`.

**Comment by ivanterziev-r3** [comment]
Rollback of /example-code and /whitepaper dirs back under /docs dir until new code example process is in place.
@fenryka @mnesbit @wzur-r3

**Pull request merged**
