### PR TITLE
Perform signature verification checks in parallel

### PR DESCRIPTION
**Pull request by nitesh7sid**
* This PR performs signature verification checks in parallel. Signature verification algorithms can become expensive depending on the key-size, message, etc and this checks can be done independently by leveraging multiple cores of hardware to improve performance. 
* Defaulting to java stream API's for parallelism

@mikehearn does that sound right?

### CODE REVIEW

**Comment by mikehearn** [comment]
It looks OK - does this lead to any observed increase in performance or is it just something you noticed whilst reading the code? I'll ask Mr Performance (Rick) to take a look.

**Comment by nitesh7sid** [comment]
I noticed it while reading the code. I haven't done any performance test on Corda yet.

**Comment by rick-r3** [comment]
Note it fails unit tests because the exception does not propagate correctly.

**Comment by nitesh7sid** [comment]
Resolved! I guess lambda was causing an issue in propogating back the exception.

**Comment by shamsasari** [comment]
@nitesh7sid there are still unit test failures.

**Comment by roastario** [comment]
Can one of the admins verify this patch?

**Comment by vkolomeyko** [comment]
This PR is now in conflicted state and needs resolving...
Also, there is no more `master` branch.

**Comment by nitesh7sid** [comment]
@vkolomeyko I have raised another PR https://github.com/corda/corda/pull/5843 on branch `release/os/4.4`

**Pull request closed without merging**
