### PR TITLE
Merge from OS 4.4 up to bc410b4.

### PR DESCRIPTION
**Pull request by chrisr3**
Merge from OS 4.4 up to bc410b4c993972951651fabca0d2ae9b99bd1ff8.

### CODE REVIEW

**Review by Schife — DISMISSED** [review]
Changes look good

**Review by roastario — DISMISSED** [review]

**Comment by chrisr3** [comment]
run tests: slow

**Comment by chrisr3** [comment]
run tests: slow

**Review by Schife — APPROVED** [review]

**Review by relyafi — APPROVED** [review]

**Review by adelel1 — APPROVED** [review]
My changes look ok

**Review by kyriathar — APPROVED** [review]
My changes look good

**Review by VCAMP — APPROVED** [review]
LGTM

**Review by roastario — APPROVED** [review]

**Review by mnesbit — APPROVED** [review]
OK

**Pull request merged**
