### PR TITLE
CORDA-3689: Fix scanning AppClassLoader on Java 11.

### PR DESCRIPTION
**Pull request by chrisr3**
* ~Do not use AppClassLoader as ClassGraph override to fix scanning on JDK11.~
* Revert CORDA-1575 to prevent CordaRPCClient logs from being clobbered.

~We are still using ClassGraph 4.8.58 for now, because the only way that ClassGraph can obtain the application jar URLs on Java 11 is by reading the `java.class.path` system property. The latest version of ClassGraph (4.8.67) does not change this.~

* Upgrade to ClassGraph 4.8.68 which falls back to reading `java.class.path` automatically.

### CODE REVIEW

**Comment by chrisr3** [comment]
run tests: smoke

**Review by adelel1 — DISMISSED** [review]
OK

**Comment by chrisr3** [comment]
run tests: slow

**Comment by chrisr3** [comment]
run tests: smoke

**Comment by chrisr3** [comment]
run tests: slow

**Review by adelel1 — APPROVED** [review]

**Pull request merged**
