### PR TITLE
CORDA-1686: Make "rpc-client-sender" daemon (#3455)

### PR DESCRIPTION
**Pull request by vkolomeyko**
Such that they do not prevent application that started them from exiting.

(cherry picked from commit 3492350)

### CODE REVIEW

**Comment by fenryka** [comment]
What does this enable? does this only impact DemoBench?

**Comment by vkolomeyko** [comment]
Jira: https://r3-cev.atlassian.net/browse/CORDA-1686 has details.

So yes it impacts DemoBench + when people close Explorer GUI there is a dangling Java process remains on Windows at least that has to be killed manually.

**Comment by vkolomeyko** [comment]
This is now dependant on #3689 being merged.

**Comment by vkolomeyko** [comment]
There is no clarity which additional OS branch either than `master` should receive those changes and no-one aggressively asking for this fix.
Closing PR without merging.

**Pull request closed without merging**
