### PR TITLE
CID-1154 reliable finality merge to OS

### PR DESCRIPTION
**Pull request by lankydan**

### CODE REVIEW

**Comment by rick-r3** [comment]
Be very careful with the OS -> ENT merge following this.  We need to retain the ENT versions of a lot of these tests since they switch between state machine implementations.

**Comment by rick-r3** [comment]
I suggest both @lankydan and @blsemo need to be happy with this PR in my absence

**Review by mnesbit — APPROVED** [review]
OK

**Review by blsemo — APPROVED** [review]
LGTM

**Pull request merged**
