### PR TITLE
Vault Query Sort by StateRef (or constituents: txId, index)

### PR DESCRIPTION
**Pull request by josecoll**

### CODE REVIEW

**Comment by mikehearn** [comment]
Aren't staterefs random? What's the use case for this?

**Comment by josecoll** [comment]
Whilst updating our samples and tutorials I came across code that was sorting (in memory) and displaying a queried result set by StateRef.

**Comment by mikehearn** [comment]
Yeah but maybe the sample was just weird/badly thought out. What was it attempting to actually do? Sorting by hash is basically a random ordering, which seems like an odd think to support in the API.

**Comment by josecoll** [comment]
Given a StateRef is the unique identifier of a State, it may be useful to provide reports / UI summaries by ordered stateRef.

**Pull request merged**
