### PR TITLE
ENT-6378 Migrate `corda-shell` to external repo

### PR DESCRIPTION
**Pull request by lankydan**
Remove the shell code from the OS code base, this includes the modules:

- `:tools:shell`
- `:tools:shell-cli`

The shell will be run within a node if it exists within the node's `drivers` directory. This is done by using a `URLClassloader` to load the `InteractiveShell` class into Corda's JVM process and running `startShell` and `runLocalShell`.

### CODE REVIEW

**Review by adelel1 — DISMISSED** [review]
LGTM

**Comment by chrisr3** [comment]
What about poor ol' DemoBench, which launches each node attached to a terminal emulator _precisely_ so that users can operate the node via the Corda shell? It sounds like DemoBench will now need to copy the `corda-shell` jar into the `drivers/` directory in the same way that it already copies the `corda-finance` CorDapp(s) into the `cordapps/` directory.

**Comment by lankydan** [comment]
> What about poor ol' DemoBench, which launches each node attached to a terminal emulator _precisely_ so that users can operate the node via the Corda shell? It sounds like DemoBench will now need to copy the `corda-shell` jar into the `drivers/` directory in the same way that it already copies the `corda-finance` CorDapp(s) into the `cordapps/` directory.

Will have a look. @adelel1 @rick-r3 Are we still supporting demobench?

**Review by adelel1 — APPROVED** [review]

**Review by taylorharvey-r3 — APPROVED** [review]
LGTM

**Pull request merged**
