### PR TITLE
Set h2 write delay to 100ms to improve performance

### PR DESCRIPTION
**Pull request by adagys**
All tests pass on my machine

### CODE REVIEW

**Comment by adagys** [comment]
h2 write delay tuning

**Comment by mikehearn** [comment]
I can't see the colours well, but why does setting even a 1 msec write delay change the scaling properties of the database? If it was just the height of the line I'd understand, but it looks from the graph like setting a tiny write delay causes processing times to become stable and even fall as more data is added to the database, but with immediate commit H2 gets slower as more data is added. That's .... weird.

At any rate, I'd be interested to hear from Rick, Matthew, Jose etc how aggressively write delays in databases they've worked with before were configured for this sort of application.

**Comment by adagys** [comment]
I wouldn't pay too much attention to the 1ms curve going down, it's only a rough plot – ran the tests once for every param on my dev machine & without any jvm warmup.

Re-running for 1ms I get:
rplot01

**Comment by rick-r3** [comment]
I can answer a couple of questions here:

1. Why does setting it to even 1 millisecond make a difference?  Looking at the H2 code, if you set it to non-zero, it flushes from a background thread, so it becomes async.  This would be consistent with the reported data above.

2. What kind of commit delay would have we seen in use before?  We would never use a commit delay normally.  Most banking systems are set up to commit synchronously without delay, and wait for replication confirmation across datacentres at a SAN level.  (i.e. they'd be using whizz bang EMC storage etc that replicates disk blocks across fibre links).

So really this is to mitigate an H2 performance bottleneck, and is H2 specific.  Naturally, we open ourselves up to (additional) data loss with this setting.  Have we checked that the data loss scenarios are not too easy to reproduce? e.g. do the integration test suite and demos run without loss unless you try really hard?  I'd expect this opens up the possibility of `kill -9` causing data loss, whereas before that shouldn't have been the case.

We need to consider the consequences.  e.g. having a disclaimer that for convenience sake everything runs against H2 in the O/S version but we know there are data loss scenarios.  This is already true, since H2 is at the mercy of the OS and underlying hardware for the resilience against data loss even with synchronous flushing within H2.

**Comment by rick-r3** [comment]
I was also going to add that H2 appear to run their benchmarks with a commit delay of 1 second.  So this might not be a code path they've focussed on heavily for performance testing.

**Comment by mikehearn** [comment]
That's what I suspected - no use of write delays in production scenarios.

The thing I still don't get any nobody has been able to tell me yet is why with synchronous commit H2 gets slower and slower over time, instead of being constantly slow. Are the codepaths very different? Or is the write-delay simply disguising the problem by putting the ever-slower commits on a background thread so we don't notice if it actually gets backlogged.

We don't actually intend the embedded H2 to be used in real deployments, it's just there for convenience, so enabling some write delay here isn't the end of the world - people are gonna benchmark on their laptops even if we tell them not to, after all, and it'd be annoying if this caused us to look artificially slow vs platforms that don't flush synchronously. 

However I suspect this change hasn't solved the problem, just made it harder to spot.

**Comment by rick-r3** [comment]
It's disguising the problem by using a background thread.  See `MVStore.setAutoCommitDelay()`

**Comment by rick-r3** [comment]
@adagys said the hot method he saw was `MVStore.getFileLengthInUse()` which iterates through the storage chunks during the commit, and the number of chunks seemed to be forever growing, causing a linear increase in commit duration.

**Comment by mikehearn** [comment]
OK. From reading the code my guess is that when WRITE_DELAY=0 compaction never occurs in MVStore, and the H2 developers didn't notice that because they always test with write delay enabled. 

We should file a bug report, but for now I'm OK with accepting this patch.  We are expecting people to point the node to a real, well administered sql db in production anyway.

**Comment by mikehearn** [comment]
Oh, just to make sure we're not at risk of slowly building up a write queue backlog, can you check Andrius that the hot method doesn't get hotter on the background thread as things run? i.e. that the backlog of queued writes don't get bigger and bigger.

**Comment by adagys** [comment]
Writes to the db file don't really queue up, the background thread just periodically checks if there are any unsaved changes and flushes them to the file (+ does some compaction). The unsaved changes do queue up, but in my tests that only resulted in a slightly increased memory footprint (nothing crazy though). I'll keep an eye on it when running longer tests.

**Comment by adagys** [comment]
filed an issue with h2 https://github.com/h2database/h2database/issues/442

**Pull request merged**
