### PR TITLE
Registers service identities in the identity service on start-up.

### PR DESCRIPTION
**Pull request by joeldudleyr3**

### CODE REVIEW

**Comment by rnicoll** [comment]
@mnesbit Joel's pointed out that we're not registering service identities in the network map, and I'm realising... in theory they're well known identities aren't they, so they should be registered?

We have secondary issues that distributed service identities fail validation, but wanted someone else to feed back on the concept while we fix that.

**Comment by joeldudleyr3** [comment]
@mnesbit This came up because the CRaSH shell is using `partyFromX500Name` to look up all parties, even notaries. If for some reason we don't want `partyFromX500Name`, we should make that clear in the description of `partyFromX500Name` and we can try fixing the shell some other way (e.g. if a party can't be found, it cycles through each node's services instead).

**Comment by mnesbit** [comment]
I have run out of time on this Joel. The integration tests fail for various CompositeKey scenarios. I have been trying to fix this up so that the code generates a chain of certs for these that is correctly signed by the Intermediate cert level, node any certificate with node level name constraints. However, this is proving fiddly.

**Comment by mnesbit** [comment]
I believe this has been handled in other commits from Patrick and others.

**Pull request closed without merging**
