### PR TITLE
ENT-11155: Remove internal Kotlin utilities which have since been added to the stdlib

### PR DESCRIPTION
**Pull request by shamsasari**
This is mostly the `Path` extension functions in `PathUtils.kt`.

### CODE REVIEW

**Comment by rick-r3** [comment]
Were we intending to try and run 4.12 code inside the external verifier running Kotlin 1.2?  This would give us problems?

**Comment by shamsasari** [comment]
> Were we intending to try and run 4.12 code inside the external verifier running Kotlin 1.2? This would give us problems?

We can always copy any of these methods into the verifier module. That way the rest of the codebase can rely on stdlib instead.

**Comment by rick-r3** [comment]
> > Were we intending to try and run 4.12 code inside the external verifier running Kotlin 1.2? This would give us problems?
> 
> We can always copy any of these methods into the verifier module. That way the rest of the codebase can rely on stdlib instead.

I suppose if we already have `core` (and the verifier) building against Kotlin 1.2 as well, it will highlight at compile time an incompatibility we have used something that isn't in one of 1.9 or 1.2.  That's what I was worried about.  Are those compilation steps in place already?

**Comment by shamsasari** [comment]
> I suppose if we already have `core` (and the verifier) building against Kotlin 1.2 as well, it will highlight at compile time an incompatibility we have used something that isn't in one of 1.9 or 1.2. That's what I was worried about. Are those compilation steps in place already?

Plan is to raise the PR for that once https://github.com/corda/corda/pull/7545 is merged. It's already been coded up.

**Review by adelel1 — DISMISSED** [review]
LGTM

**Review by adelel1 — APPROVED** [review]

**Review by rick-r3 — APPROVED** [review]

**Pull request merged**
