### PR TITLE
ES-853: update Artifactory references to new public location

### PR DESCRIPTION
**Pull request by ronanbrowne**
Prep work for migrating non authenticated artifactory repos to S3 location - Non authenticated Artifactory access will be removed in the immediate future.

These repos are replicated at https://download.corda.net/maven

### CODE REVIEW

**Review by yarivus — DISMISSED** [review]
LGTM

**Review by chrisr3 — DISMISSED** [review]
LGTM, although I am wondering if `artifactory_contextUrl` is used any more?

**Review by adelel1 — CHANGES_REQUESTED** [review]
Quasar binary has changed. Did you mean to do this?

**Comment by chrisr3** [comment]
> Quasar binary has changed. Did you mean to do this?

That binary shouldn't be necessary any more anyway. However, if the binary now matches the designated version of Quasar then it needed updating.

**Comment by ronanbrowne** [comment]
> Quasar binary has changed. Did you mean to do this?

Unintended, thanks ... let me return to it's original state, seen as any alterations to that are outside scope of this PR

**Comment by ronanbrowne** [comment]
> LGTM, although I am wondering if `artifactory_contextUrl` is used any more?

Still needed for some publishing aspects (we don't publish directly to the S3 location currently)

**Review by adelel1 — APPROVED** [review]

**Review by chrisr3 — APPROVED** [review]
LGTM

**Review by yarivus — COMMENTED** [review]
thx @ronanbrowne

**Pull request merged**
