### PR TITLE
Remove ALICE, BOB and CHARLIE

### PR DESCRIPTION
**Pull request by rnicoll**
Remove ALICE, BOB and CHARLIE test identities, which imply individuals involved in transactions
rather than organisations. Although theoretically possible, this is not a common case and we want
to avoid implying that individuals within an organisation are signing transactions personally.

### CODE REVIEW

**Comment by rnicoll** [comment]
Opening this for review early on, mostly so we can think about whether this is the correct solution, or if we should be making wider use of MEGA_CORP/MINI_CORP, or something else.

**Comment by josecoll** [comment]
Oh dear - see my latest PR

**Comment by josecoll** [comment]
ALICE, BOB and CHARLIE are used ubiquitously in 3rd party apps.
I wouldn't remove them.

**Comment by josecoll** [comment]
Refactoring for refactoring sake is a bad practice IMHO.

**Comment by mikehearn** [comment]
Lots of merge conflicts - perhaps rather than remove stuff, mark them as deprecated.

**Comment by rnicoll** [comment]
I think based on the feedback, and apparent widespread use, may just close this and make the distinguished names more corporate/less individual.

**Pull request closed without merging**
