### PR TITLE
CORDA-1312: Removed the need to have whitelist.txt for updating the c…

### PR DESCRIPTION
**Pull request by shamsasari**
…ontracts whitelist using the bootstrapper.

Instead the current whitelist is read in from the existing network parameters file.

### CODE REVIEW

**Comment by shamsasari** [comment]
The network parameters are printed and so the user sees the contents of the whitelist:
```

**Comment by tudor-malene** [comment]
A, cool.
Didn't notice that.

All good then

**Comment by chrisr3** [comment]
Is there a way to dump the whitelist to the console without doing anything else?

**Comment by shamsasari** [comment]
The whitelist is stored in the network-parameters file which is serialised using AMQP. Kat's creating a "blob inspector" for viewing such files. I'd rather rely on that than duplicating the equivalent in the bootstrapper.

**Comment by shamsasari** [comment]
Updated api-current.txt to add in the new NotNull annotation to `NetworkParameters.toString()`

**Pull request merged**
