### PR TITLE
ENT-5273 update from os 4.6

### PR DESCRIPTION
**Pull request by blsemo**
Merge latest changes from 4.6

### CODE REVIEW

**Comment by blsemo** [comment]
Run tests: slow, smoke

**Review by lankydan — DISMISSED** [review]
sorry again for the pain merging my tests 😢  🙏

**Comment by blsemo** [comment]
Run tests: slow, smoke

**Comment by blsemo** [comment]
Run tests: smoke, slow

**Review by lankydan — APPROVED** [review]

**Pull request merged**
