### PR TITLE
Fixed broken links in GitHub PR template

### PR DESCRIPTION
**Pull request by todofixthis**
See description in #5475 for context.

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Thanks for your code, it's appreciated! :)

### CODE REVIEW

**Comment by roastario** [comment]
Can one of the admins verify this patch?

**Review by lockathan — DISMISSED** [review]
LGTM

**Review by lockathan — CHANGES_REQUESTED** [review]
Hi. Sorry, please can you add the Developer's Certificate of Origin to this PR? Then I can merge it.

**Comment by todofixthis** [comment]
I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).

**Review by lockathan — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
