### PR TITLE
Fix the RAFT notary demo, previously only 1 of the notaries was used

### PR DESCRIPTION
**Pull request by andr3ej**

### CODE REVIEW

**Comment by chrisr3** [comment]
When I follow [these instructions](https://docs.corda.net/running-the-demos.html#raft-notary-demo) for M11, it produces the following output:
```
Connecting to the recipient node (localhost:10003)
Notary: "Raft", with composite key: net.i2p.crypto.eddsa.EdDSAPublicKey@50a9b242
Notarised 10 transactions:
Tx [D26B9B..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [761BA6..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [83C9C3..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [02C1D2..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [3F321F..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [0A9C92..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [206FAC..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [DB9189..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [87E2FE..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
Tx [307E65..] signed by DL8cJ4Hb5Nht4nns792TJ1gwbsNUxpEbPpGy5xfCMykk2h
```
which would seem OK. How does your PR affect this?

**Comment by andr3ej** [comment]
The instructions say "You will notice that successive transactions get signed by different members of the cluster (usually allocated in a random order)." but in your output it's always the same member of the cluster.

**Comment by chrisr3** [comment]
Interesting. The `cordformation` plugin removes whitespace from the legal name anyway, and so this was broken even with the v0.11.1 of the gradle plugins. Oops.

**Comment by rnicoll** [comment]
LGTM, thanks for this

We should probably move node name derivation into a shared function at some point so it's consistent throughout.

**Comment by andr3ej** [comment]
I'm currently working on this demo so there will be changes to make it less brittle, this PR is to get it into a working state as a first step.

**Pull request merged**
