### PR TITLE
EG-177   Network Parameter Hotloading

### PR DESCRIPTION
**Pull request by pnemeth**
EG-177
Network Parameter Hotloading

### CODE REVIEW

**Review by JamesHR3 — APPROVED** [review]
Approving on basis of previous review.

**Review by anuragr3 — APPROVED** [review]
LGTM

**Comment by rekalov** [comment]
Err, I though we wanted to do QA on a feature branch?

**Comment by rekalov** [comment]
Bringing wider audience to review. Technically this fix looks good but it may break things conceptually:
* We don't know the impact on existing flows running issuing flag day, as different nodes may run with different network parameters versions
* We are removing possibility to shutdown nodes on a flag day with notary only change

Are we OK to do all QA stuff directly in 4.6 or do we need separate testing?

@rick-r3 , @mnesbit  - opinions?

**Comment by JamesHR3** [comment]
> Err, I though we wanted to do QA on a feature branch?

I originally suggested a feature branch in case we wanted to do follow ups to the original PR, but I wasn't expecting QA to run on it. I don't think they're set up to do so.

**Comment by anuragr3** [comment]
> * We don't know the impact on existing flows running issuing flag day, as different nodes may run with different network parameters versions
> * We are removing possibility to shutdown nodes on a flag day with notary only change

That was the feature that was requested: To not require node shutdown on notary only change. Are you asking if there is code somewhere that assumes a flag day will always lead to shutdown and this contract will break as a result of this feature?

**Comment by rekalov** [comment]
> > * We don't know the impact on existing flows running issuing flag day, as different nodes may run with different network parameters versions
> > * We are removing possibility to shutdown nodes on a flag day with notary only change
> 
> That was the feature that was requested: To not require node shutdown on notary only change. Are you asking if there is code somewhere that assumes a flag day will always lead to shutdown and this contract will break as a result of this feature?

It's not necessarily the code. There should be no issues if the flows will continue running smoothly. However, if the flows will be disrupted, one may hypothetically prefer to have predictability and one minute downtime (until the nodes will be auto-restarted) rather than unpredictable behavior during 10 seconds.

**Comment by anuragr3** [comment]
> It's not necessarily the code. There should be no issues if the flows will continue running smoothly. However, if the flows will be disrupted, one may hypothetically prefer to have predictability and one minute downtime (until the nodes will be auto-restarted) rather than unpredictable behavior during 10 seconds.

I think the whole point of this feature is to reduce downtime. 

If flows are disrupted they can pick up from checkpoints. If we are adding a notary a bit of unpredictability around flag day - which by the way is recovered from automatically - should be acceptable.

**Comment by mnesbit** [comment]
The feature is to reduce flag days as the 'approval' process is very disruptive and consensus between many firms is a painful chain of emails.

If we are concerned that there are corner cases then might I suggest a change in the logic. Basically people are adding new notaries, they are not generally removing them. (Reordering of the notaries list is possible too whilst this occurs, but we try not to as people who coded notaries.first in cordapps get a rude surprise). The edge cases to my mind are all related to removal of a notary. Therefore allow hot loading for notary addition and fallback to hard flag day if any notary is removed. Transactions carried out under an existing notary will not care if their transactions have a faintly stale network parameters, since their notary is not changing.

**Review by rekalov — APPROVED** [review]
My impression is that network map won't remove old notary from network parameters at all, even if you remove it from network-parameters.conf. The Q was only for new notary onboarding.
If you think it's fine for existing flows, I can give my approval as a codeowner.

**Comment by anuragr3** [comment]
> The feature is to reduce flag days as the 'approval' process is very disruptive and consensus between many firms is a painful chain of emails.
> 
> If we are concerned that there are corner cases then might I suggest a change in the logic. Basically people are adding new notaries, they are not generally removing them. (Reordering of the notaries list is possible too whilst this occurs, but we try not to as people who coded notaries.first in cordapps get a rude surprise). The edge cases to my mind are all related to removal of a notary. Therefore allow hot loading for notary addition and fallback to hard flag day if any notary is removed. Transactions carried out under an existing notary will not care if their transactions have a faintly stale network parameters, since their notary is not changing.



> My impression is that network map won't remove old notary from network parameters at all, even if you remove it from network-parameters.conf. The Q was only for new notary onboarding.
> If you think it's fine for existing flows, I can give my approval as a codeowner.

Ok I am going to merge this change now. I feel that dealing with notary removal and notary re-ordering is a separate topic best addressed in a different ticket. Hotloading makes the problem more immediate but isn't the source of the problem.

**Pull request merged**
