### PR TITLE
CORDA-2617: Add failover listeners to terminate node process

### PR DESCRIPTION
**Pull request by vkolomeyko**
This is a backport of changes done in Corda Enterprise.

It will be triggered in case of:
a) Loss of connectivity to in-built Artemis for Bridge Control;
b) Loss of connectivity to in-built Artemis for P2P connectivity.

Note on merge to CE: Disregard these changes and take whatever CE already has.

### CODE REVIEW

**Comment by gendal** [comment]
does this need any release notes, docs or changelog?  presumably it means people will see nodes shutting down more often.  it will be a *good* thing... they don't just hang any more...!  but should we use this as an opportunity to tell them to expect it and what they should do?

**Comment by vkolomeyko** [comment]
> does this need any release notes, docs or changelog? presumably it means people will see nodes shutting down more often. it will be a _good_ thing... they don't just hang any more...! but should we use this as an opportunity to tell them to expect it and what they should do?

Sure - I will update the docs mentioning when node may shut down "by itself".

**Comment by vkolomeyko** [comment]
Currently blocked by: https://github.com/corda/corda/pull/5339

**Comment by vkolomeyko** [comment]
@adagys and @mnesbit - could you review and approve the changes, please?

**Pull request merged**
