### PR TITLE
unify references to notary in output

### PR DESCRIPTION
**Pull request by s-matthew-english**
harmonize line 167 with earlier references on line 146 for example

### CODE REVIEW

**Comment by mikehearn** [comment]
Thanks!

**Comment by s-matthew-english** [comment]
@mikehearn yeah for sure, generally think the code base looks pretty solid. do you think there's any chance one of the corda devs or someone from r3 might be interested to come speak at our meet up group in cologne/stuttgart or dusseldorf?

**Comment by mikehearn** [comment]
Good question! I do enjoy visiting Germany when I get the chance! I'll ask around, I don't think we have anyone there but will let you know - otherwise please do organise a meetup regardless! I'm sure we could arrange a video call if nobody is free to come out and visit!

**Comment by s-matthew-english** [comment]
ah, that's great! maybe we can discuss by email to figure out the details? if you like you can reach me at '_s.matthew.english@gmail.com_'

**Pull request merged**
