### PR TITLE
Corda runs powered by Spring Boot.

### PR DESCRIPTION
**Pull request by sollecitom**
**DO NOT MERGE!**

Refactored `Corda.kt` to leverage Spring Boot as a Dependency Injection container.

How to run it:
- Run/debug `Corda.kt` from Intellij with program arguments `--config-file=node/src/main/resources/testnode.conf` and Quasar agent.

- Run/debug `TestCorda.kt` to see how Spring Boot lets you override implementations in tests (from Intellij with program arguments `--config-file=node/src/main/resources/testnode.conf` and Quasar agent).

Notes:

- The logging is slightly different than the original format. I believe it can be fixed quite easily but it was beyond the scope of this spike.
- It took me ~15m to make it work.
-  Here's a PR showcasing Guice instead (https://github.com/corda/corda/pull/2131).

### CODE REVIEW

**Comment by sollecitom** [comment]
Guys please have a look so we can decide whether we want to go forward. This is just an idea, this PR will never be merged.

**Comment by exFalso** [comment]
inb4 storm of comments. I'd like to quickly mention another use case for DI: enterprise feature injection. Our current "top-down" enterprise feature specialisation will not and does not scale to the whole codebase, especially if the to-be-injected feature lives in some submodule of the system.
I think DI *is* the right solution for open-source vs enterprise feature switching, this will allow simple interface-based specification of features, an introduction of an enterprise feature will not result in a log(n) change in the code tree and in general will minimise long term hair loss.
I view cordapp injection and e.g. node initialisation dependency graph resolution as an additional potential use case, to me enabling easy enterprise dev is a good enough reason to introduce DI in and of itself.

**Comment by sollecitom** [comment]
@exFalso plugin-based resolution at runtime is exactly the use case we have this Sprint. It would allow a clean switch at runtime without polluting the classpath with multiple implementations that are never required at the same time.

**Comment by andr3ej** [comment]
further to @exFalso's comment, currently it's difficult to replace a service for testing and it always has to be done in a bespoke way, see how VaultSoftLockManagerTest hacks the vault service. a DI solution should provide a general mechanism for swapping out services in tests.

**Comment by sollecitom** [comment]
@andr3ej yeah, I agree. Fortunately Spring Boot in particular makes substituting a service in a test quite a simple task. All that's needed is to create a Kotlin Spring `@Configuration` annotated class that imports the production one, excludes the production scoped service, and provide a test scoped one.

With a bit of wrapping, this can be done with just a few lines of code.

**Comment by sollecitom** [comment]
@andr3ej Run/debug `TestCorda.kt` to see how Spring Boot lets you override implementations in tests (from Intellij with program arguments `--config-file=node/src/main/resources/testnode.conf` and Quasar agent).

**Comment by andr3ej** [comment]
since apparently this isn't going away, some things i hate about spring:
* does too much, none of its parts as good as dedicated libs, like buying only microsoft
* doesn't play well with other libs in the di space as hackability so poor
* spring way or highway, vendor lock-in
* can't integrate with code without polluting it with its annotations
* astonishingly crude config system with call site defaulting and key composition, you never know when a key is safe to delete
* terrible error messages that point you to where your autowiring problem isn't
* autowiring arrays does not work
* ignores visibility modifiers
* not practical to use context in an ad-hoc way as it's so slow
* i have to be a spring expert now which i find quite distasteful
* spring absolutely loves aop
* huge list of bean lifecycle steps to remember
* "bean"
* same team that brought us 50k lines of undebuggable xml
* too magic e.g. how the devil does that test override example work
* facilitates poor software engineering e.g. circular deps, setters

**Comment by chrisr3** [comment]
So speaking as a Spring Boot N00b, I am assuming here that this example works because there's only one `ExampleService` bean to be injected anywhere. How would it handle ambiguous bean resolution? Also, my experience with CDI/WELD was that beans could only be injected into other beans, which meant that suddenly _everything_ had to become a bean. (WELD never solved the problem of which order to destroy beans in either.)
For reference, having using CDI/WELD considerably in the past, I would _never_ have recommended using it for Corda...

**Comment by sollecitom** [comment]
@andr3ej 

I do not have strong feelings about Spring Boot, I'm more than happy to use another DI container, provided someone creates a similar branch with the same features. I have a feeling some of your concerns might be related to previous versions of the Spring / Spring Boot framework, but here are my thoughts about your questions:

- does too much, none of its parts as good as dedicated libs, like buying only microsoft : it's an extremely modular project actually.

- doesn't play well with other libs in the di space as hackability so poor : not sure what you mean, would you use multiple di libs together? An example?

- spring way or highway, vendor lock-in : they actually made quite a bit of effort for this not to be the case, look at allowing usage of non-Spring annotations.

- can't integrate with code without polluting it with its annotations : as above, I'm not using any Spring annotation in this example. Also, other configuration means do exist, based on manual binding or file configuration.

- astonishingly crude config system with call site defaulting and key composition, you never know when a key is safe to delete : what config system? Do you refer to injecting values? Not a big fan either, but we don't have to use it.

- terrible error messages that point you to where your autowiring problem isn't : if you try to remove the annotation from `LoggingExampleService` and run the application it will tell exactly where the problem is.

- autowiring arrays does not work : not sure about arrays, but `LIst` and `Set` do work.

- ignores visibility modifiers : not true anymore, works with internal but not private.

- not practical to use context in an ad-hoc way as it's so slow : not sure what you mean.

- i have to be a spring expert now which i find quite distasteful : I disagree, production usage I saw wasn't much different from showcased simple wiring.

- spring absolutely loves aop : not sure and don't see what the problem would be.

- huge list of bean lifecycle steps to remember : not sure what you mean.

- "bean" : :)

- same team that brought us 50k lines of undebuggable xml : frameworks do evolve, as do the teams behind them.

- too magic e.g. how the devil does that test override example work : it works by Spring knowing what test scope is, but I don't get what's the problem with it.

- facilitates poor software engineering e.g. circular deps, setters : true, like most DI containers, although we can enforce constructor dependencies only, like the example.

**Comment by sollecitom** [comment]
@chrisr3 about your comments:

- Naming disambiguation: in case more than one candidate is found when the dependencies tree is constructed, Spring terminates the application with an error, complaining about an ambiguous setup. Solving it requires adding a qualifier at the injection point (can be based on the name or other factors). From previous experiences this pretty much never happens.

- About everything needing to be managed by the DI container, well, yes, but it is up to us to decide what gets injected and what doesn't. Usually, implementations that are defined at runtime get managed by the DI container at high level, and injected into types at high level, meaning that the number of them tends to stay contained.

**Comment by chrisr3** [comment]
@sollecitom Looking closer, it seems that `@Named` is in fact a simple CDI qualifier! However, I'm suspecting that Spring Boot does not also support creating custom additional Qualifier annotations with optional parameters for passing metadata - correct? (With CDI, your Qualifier's parameters could be either "binding" or "non-binding", where "non-binding" values were ignored by the container's bean resolution logic. Conversely, `@Named`'s `name` parameter here is apparently a "binding" one.)

Does Spring Boot allow for the injection of things which _aren't_ beans, i.e. POJOs, generated values etc?

**Comment by al-r3** [comment]
@chrisr3 @sollecitom 
In my experience using other DI in case of conflicts (which were quite common in my workplace)
One creates an annotation annotated with: @Qualifier and that becomes "part of the type" you're injecting.

**Comment by chrisr3** [comment]
@al-r3 For my previous employer, I wrote a CDI "configuration library" JAR that allowed system properties and other configuration values to be injected into beans as simple POJOs. This library used the Full Monty of CDI, including custom `@Qualifier`s, beans with `@Produces` / `@Disposes` methods, "eager" beans created by observing events and `@Alternative` producers ranked by `@Priority`.

And this experience has taught me _not_ to recommend using CDI/WELD in Corda ;-).

**Comment by andr3ej** [comment]
the little bit of spring in corda is already causing problems. can someone explain to me how IRSDemoTest is supposed to find InterestRatesSwapDemoAPI when running from intellij? an example of spring magic wasting development time.

**Comment by sollecitom** [comment]
@andr3ej let's not confuse a specific problem with our own usage of a technology in a particular demo with the merits of the technology themselves.

**Comment by andr3ej** [comment]
it's a big minus if it makes it this easy to screw up

**Pull request closed without merging**
