### PR TITLE
Make `extraCordappPackagesToScan` on Node Driver a Set.

### PR DESCRIPTION
**Pull request by vkolomeyko**
This is probably not the most exciting change, but having `List` feels a bit awkward when it is not the order, but rather the content that counts and passing duplicates doesn't quite make sense.

### CODE REVIEW

**Comment by andr3ej** [comment]
i don't like it. yes it's logically correct, but now we're forcing java users to use a lib

**Comment by rnicoll** [comment]
`com.google.common.collect.Sets`? I suppose so, but given it'll be a dependency of Corda anyway is that a problem?

**Comment by vkolomeyko** [comment]
Yes, I have not changed any of the Gradle files, so dependency been already there.
@andr3ej - do you think it would be better if I take out Guava import from `VaultQueryJavaTests` and replace `Sets.newHashSet` with my own helper method that does the same?

**Comment by andr3ej** [comment]
let's not complicate things further by adding another helper. sets are a much more expensive way to pass things around than lists, and cordappPackages is typically literal data so using a set doesn't even do anything in practice, and by making it a set you're kind of outsourcing logic that should be in CordappLoader. on balance i can't justify this change, but feel free to get another opinion e.g. @shamsasari

**Comment by vkolomeyko** [comment]
Sure, @shamsasari - what do you think about this change?

@andr3ej 
Re: sets are a much more expensive way to pass things around than lists
Could you elaborate a bit more on that, please?
Also, earlier you've said "it's logically correct" and this is the main point of this PR is to use correct collection data structure to clearly indicate that this is a sequence of *distinct* entries.

**Comment by vkolomeyko** [comment]
@shamsasari - could you have a look at this PR today, please?

@andr3ej - there were few outstanding questions from last week:
Re: sets are a much more expensive way to pass things around than lists
Could you elaborate a bit more on that, please?
Also, earlier you've said "it's logically correct" and this is the main point of this PR is to use correct collection data structure to clearly indicate that this is a sequence of *distinct* entries.
Could you please reply today?

**Comment by vkolomeyko** [comment]
OK - fair enough. I will close this PR without merging.
Thanks all.

**Pull request closed without merging**
