### PR TITLE
INFRA-357 - Add release tag Jenkins build for OS 4.4

### PR DESCRIPTION
**Pull request by cairncross**
### Changes
This PR modifies the release branch regression test Jenkinsfile so that it can be used to build release tags. The only difference between the two scenarios is that the summary email is not sent in the case of release tag builds.

Tags matching `^release-V(d+\.\d+){0,1}(\.d+){0,1}(-.+){0,1}$` will trigger a build.

The Jenkins job configuration will mirror this test example in [ci03](https://ci03.dev.r3.com/job/release-tag-test/configure), except the repository will be set to `corda` or `enterprise` as appropriate, and the above regular expression will be used for the tag discovery name filter.

### CODE REVIEW

**Comment by wzur-r3** [comment]
@cairncross this Jenkinsfile looks very familiar. Perhaps we could have a single Jenkinsfile for snapshot publishing and for an actual release?

**Comment by wzur-r3** [comment]
This looks good to me, but it has to be tested thoroughly to make sure regression build is not affected by this change

**Comment by cairncross** [comment]
I tested this on ci03 by modifying the tag regex in the Jenkinsfile to match against test tags `ci03-test-...` and configuring the job to build a substitute test branch. https://ci03.dev.r3.com/job/release-tag-test/

When pushing a tag, the summary email block was skipped as intended and commits to the branch triggered the summary email block.

The unit / integration test etc. steps themselves were omitted for brevity, considering that no changes have been made to them.

**Review by wzur-r3 — APPROVED** [review]
LGTM

**Pull request merged**
