### PR TITLE
Eg 197

### PR DESCRIPTION
**Pull request by luca-debiasi-r3**
The "initial-registration" sub-command continues starting the node. 

# PR Checklist:

- [X] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs? **Not needed: there are no functions changed signatures or new references to objects exposed.**
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)? **CorDapps developers not affected.**
- [X] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

### CODE REVIEW

**Comment by JamesHR3** [comment]
4.6 and 4.7 are further out of sync than I thought, which is why there's a lot of extra commits in this PR. It looks like a 4.6 -> 4.7 merge is currently in progress which should tidy this up. If that doesn't help then you'll probably have to create a new branch off 4.7 and raise a new PR with your changes in that way, but hopefully that won't be the case.

**Review by mnesbit — CHANGES_REQUESTED** [review]
I do not feel that the design requirements for initial-registration have been adequately discussed amongst the group leads and probably we need to analyse what product expect too.

**Comment by vkolomeyko** [comment]
@mnesbit @JamesHR3 - do we still need this PR or can it be closed?

**Comment by mnesbit** [comment]
Probably not, but @adelel1 should put it back into bug triage

**Pull request closed without merging**
