### PR TITLE
migrate PersistentIdentityService to use key.toShortString()

### PR DESCRIPTION
**Pull request by roastario**

### CODE REVIEW

**Comment by gendal** [comment]
are there any tests (manual or automated), especially for the migration?   release notes? changelog?   what was the conclusion with respect to whether a lightweight design was needed.   (and is this targeted at 4 or 5)?

**Comment by roastario** [comment]
> are there any tests (manual or automated), especially for the migration? 

No. We have designed corda on to avoid this possibility. The migrations are run as part of the process of building the datasource for the node, and as we do not allow "injection" (aka passing a parameter to a constructor) it is impossible to, at runtime, determine what scripts to run. 

>  release notes? changelog?

I don't think this needs release notes / changelog as it's 100% not exposed. 

> lightweight design ?

Yes we can do this, but I was just testing if it was possible first. 

>  (and is this targeted at 4 or 5)?

Both preferably, as we need this for accounts.

**Comment by gendal** [comment]
hence the question about manual. if we can't test something automatically, there presumably needs to be an R3T ticket instead?

if this is just a test PR than fine but if it's going into the product we probably do need release notes (what does an operator do if the migration fails for some reason? will we have tested it on every supported database?  what happens if they have a ton of records to update across a slow connection. does it make it look like the node startup (or migration script execution) has hung?)

**Comment by rick-r3** [comment]
How does relate to https://github.com/corda/corda/pull/5217 ?

**Comment by roastario** [comment]
> How does this relate to #5217 ?

This is v4 version of that change. Originally I had hoped to get it into 4.1, but now that that is impossible. I will close this and backport it as normal.

**Pull request closed without merging**
