### PR TITLE
:experimental:certgen

### PR DESCRIPTION
**Pull request by cxyzhang0**
@jamesbr3 Hi James, I see people asking about custom certificate generation for an Corda Network. I thought it may help to share some of my codes used to create certificate jks files based on the X509Utilities. The command line and configuration parsers are following your netparams example. 
There are two commands: cert and csr.
Use cert to create the jks files for all the entities in the network as defined by a configuration. One sample configuration is provided in resources/cert_defs.conf. The node certs follow the pattern in which all three are issued by DOORMAN_CA and NODE_CA cert is a dummy one with CA BasicConstraint being false. 

Use csr to generate CSR p10 files for the nodes and separately store the keys in jks. One sample configuration is provided in resources/csr_defs.conf.  This workflow is for a network which has a certificate issuing service similar to tCN's Doorman. Once the CSRs have been approved and certificates issued, there needs to be a tool to package the public certificates and the keys into jks used by Corda. The latter is yet to be developed.

Please review and let me know if it is a worthy exercise. If yes, any changes/improvements necessary. 

Thanks.

\Sean

### CODE REVIEW

**Comment by mikehearn** [comment]
Thanks for the contribution Sean! I've asked James to take a look.

**Comment by roastario** [comment]
Can one of the admins verify this patch?

**Comment by nargas-ritu** [comment]
Internal backlog ticket [CORDA-4198](https://r3-cev.atlassian.net/browse/CORDA-4198)

**Comment by marcellofarina75** [comment]
Hello [cxyzhang0](https://github.com/cxyzhang0),
thank you for your contribution to Corda!

Our engineers reviewed your Pull Request and established that, while your proposal would definitely improve Corda, the work needed to merge it (in terms of unit, integration and regression tests, documentation updates, security assessments, and ongoing maintenance) would prevent us from shipping features and fixes that are prioritised higher in our roadmap (which is driven directly from inputs from across the user base).

So this means we regretfully need to let you know that your PR will be declined.

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information

**Pull request closed without merging**
