### PR TITLE
Uses brute-force approach to add a dropdown.

### PR DESCRIPTION
**Pull request by joeldudleyr3**

### CODE REVIEW

**Comment by joeldudleyr3** [comment]
Hey Clinton, this is the brute-force approach to adding a dropdown in the docs - I've added every link by hand. Would it be difficult to include this in the release process checklist? We can always revisit automating it later.

**Comment by joeldudleyr3** [comment]
@Clintonio As in only in layout_for_website.html? It's in both currently.

**Comment by Clintonio** [comment]
It's best to have it in only one. It might be a little bit of a PITA to test but having it in only one place will be easier to maintain and won't have links to an external site from a dev version of the site.

**Comment by joeldudleyr3** [comment]
Done - back to you

**Comment by Clintonio** [comment]
Also ensure the docs build passes for this one, it's ignorable but I'd rather see it pass here.

**Pull request merged**
