### PR TITLE
CORDA-3868: Use specific exception to determine SSL handshake timeout

### PR DESCRIPTION
**Pull request by vkolomeyko**

### CODE REVIEW

**Review by rekalov — APPROVED** [review]
Looks good. I think the biggest challenge is write test for this.

**Comment by vkolomeyko** [comment]
@rekalov 
> write test for this

I am not sure how practical this is. Exception in question comes deep inside from Netty. The only way to write a useful test is to somehow simulate a timeout.

**Comment by rekalov** [comment]
Yes, the test should simulate timeout (you can set it to lower value for test) and make sure that the client can reconnect after. We should try to cover also every other error which we handle to exclude from badCert. The main purpose is to catch regressions during next netty upgrade, if they e.g. change change exception type or messages.

Most likely, it won't even require AMQP client, rather simple socket with TLS support - as was suggested by @mnesbit on Friday.
Though, we can implement it separately from this PR if we want to, just need a Jira to track.

**Comment by vkolomeyko** [comment]
Thanks @rekalov - I do agree. Jira raised: https://r3-cev.atlassian.net/browse/CORDA-3871

**Review by mnesbit — APPROVED** [review]
OK

**Pull request merged**
