### PR TITLE
Add support for multiple hash algorithms

### PR DESCRIPTION
**Pull request by mvdbos**
This PR is a draft, purely for discussion purposes. It is an addition/alternative to #6273,

This PR tries to achieve the following:

- Introduce new hash algorithms for SecureHash. As suggested [here](https://groups.io/g/corda-dev/message/1274) by @mikehearn, it is currently done explicitly by adding children to the sealed `SecureHash` class, instead of in a more flexible way. This would leave R3 fully in control of which algos are enabled. I am very much open to discussion on this, as the approach in #6273 seems much more flexible. 
- Don't break the current code base that assumes SHA256 everywhere. Essentially, this new code is not used anywhere yet and there are no API breaks. I am in favor of separating into two PRs 1) the enabling of hash agility in SecureHash, from 2) the implementation in the Corda plartform everywhere. This would make PR 1 far easier to get merged, which would enable my use case (which doesn't require standard Corda to use it, but enables me to produce SecureHashes for differnet algos).
- Introduce a way to inject a SecureHash-producing service into places where hashes need to be created and where those places should be unaware of which type of SecureHash is being generated. In this PR that is the `DigestService` interface. Essentially, for each type of `SecureHash`, there should be an associated `DigestService`. Added benefit: such a service is perfectly suitable to be a `@CordaService`.

@chrisr3 : looking forward to your comments.

### CODE REVIEW

**Comment by chrisr3** [comment]
Given a string of 64 hexadecimal digits in a database column or a JSON document, how could I recognise which type of `SecureHash` object it represents?

**Comment by mvdbos** [comment]
> Given a string of 64 hexadecimal digits in a database column or a JSON document, how could I recognise which type of `SecureHash` object it represents?

This is indeed not possible. In #6273 it is, and that might be a better approach for the SecureHash-part of that. That said, can you give me an example of where this capability is required? As far as I know, the current code makes assumptions on what type of hash it expects. If that remains the case, there shouldn't be a problem? I am probably missing something.

**Comment by chrisr3** [comment]
> That said, can you give me an example of where this capability is required?

I am assuming that we would like to create transactions based on alternate digest algorithms, in which case transaction IDs will need to be persisted into and read from the Vault. See the low-level "soft-locking" services in `NodeVaultService`,

**Comment by mvdbos** [comment]
> > That said, can you give me an example of where this capability is required?
> 
> I am assuming that we would like to create transactions based on alternate digest algorithms, in which case transaction IDs will need to be persisted into and read from the Vault. See the low-level "soft-locking" services in `NodeVaultService`,

Ok, I will have a look at that. But once a tx id is created and persisted, do we care what type it is when we read it from the Vault or use it to refer to a tx in other places? We can't do any reversing on it anyway, right? Once the Merkle root is calculated, it is a dumb bytearray, and we can still recalculate the Merkle root, since the code will know how to do that? Or do you envision a ledger where there is a mix of transactions that use different algos?

* Only caveat is that the digest length should fit in the db, but that applies even more to a more flexible solution.

**Comment by chrisr3** [comment]
> But once a tx id is created and persisted, do we care what type it is when we read it from the Vault or use it to refer to a tx in other places?

We certainly do. For example, if the soft-locking algorithm persisted a `FOO256` transaction ID but read always read it back from the database as a `SHA256` object then `NodeVaultService` would fail to find the soft-locked states to unlock them again.

**Comment by mvdbos** [comment]
> We certainly do. For example, if the soft-locking algorithm persisted a `FOO256` transaction ID but read always read it back from the database as a `SHA256` object then `NodeVaultService` would fail to find the soft-locked states to unlock them again.

Ah, I see whay you mean. In a few places `SecureHash.parse` is used, which is now SHA256 by default. 

Your solution in #6273, where the hash contains some info about the algo, indeed addresses this  and has the possible added benefit that it enables easier migrations when switching algos on a live network. I am happy to go this way. If we assume that, would you be open to splitting out the hash creation logic in your PR into something like the `DigestService` seen here? 

For the sake of completness two other options to explore, so please shoot down if not valid in your opinion: 

1. To make the used algo be part of the network parameters and have the `parse` method be part of an injected `DigestService`. This would keep the persisted hashes opaque, and put the responsibility on the code and config to know how to decode them. Downside is that this would make migrations harder: it would mean any tx with an older network parameters hash would have to be migrated in one go.
2. To not care about the type of SecureHash that is read (the code is currently not acting differently anywhere based on hash type) and simply hex-decode the persisted hash and instantiate some generic SecureHash with it. It would probably even work with SHA256 as it is now. Or do I miss a place where this could cause problems?

**Comment by mnesbit** [comment]
My initial thoughts on this are:
1. I think we do have to make the hashes self describing when represented as strings, such that re-validation can check the type and recalculate if required. We are unfortunately forced to use this string representation often because several databases cannot index on binary data and the string performance is more optimised in general.
2. I would also like the SecureHash and related classes to be agnostic to the hash type used, because Core has to be usable in contexts outside the node as a library. We definitely have to expect legacy transactions to have old style SHA256 hashes and will always be in a mixed environment.
3. At the same time we will have to make the Corda Transaction model maintain a policy on what hashes are acceptable. This will almost certainly require an eventual addition on network parameters, which puts such changes a little way off, though we could use a local system property to let people experiment with alternate choices on private networks.
4. I am not at all sure about the custom interface for digests either, since the JCA framework provides this, but I must admit making a Custom Provider is often a royal pain. Also our internal discussions on SecurityManager would make them locked down, where as your approach is bound into the cordapp. I will need to think about the broader design here I think.

**Comment by mvdbos** [comment]
>     1. I think we do have to make the hashes self describing when represented as strings, such that re-validation can check the type and recalculate if required. 

Ok, clear. Can you help me by giving an example of where re-validation is done without the surrounding code already reasonably knowing which hash function to use? It is probably my lack of knowledge, but I can't find an example. Perhaps an example could be `SecureHash.hashConcat()`, and to me it looks like all situations it is used are aware of the hash function to use in code (hardcoded to SHA-256). If something like `DigestService` injection is possible, this would all be solved.

>     2. I would also like the SecureHash and related classes to be agnostic to the hash type used, because Core has to be usable in contexts outside the node as a library. We definitely have to expect legacy transactions to have old style SHA256 hashes and will always be in a mixed environment.

Agreed. The way this PR and #6440 are implemented, keep backwards compatibility. 

>     3. At the same time we will have to make the Corda Transaction model maintain a policy on what hashes are acceptable. This will almost certainly require an eventual addition on network parameters, which puts such changes a little way off, though we could use a local system property to let people experiment with alternate choices on private networks.

Yes, I would be very happy if we could introduce code like this, but not enable it yet formally in any way. It would allow low-level experimentation, but not be usable in production code. 

>     4. I am not at all sure about the custom interface for digests either, since the JCA framework provides this, but I must admit making a Custom Provider is often a royal pain. 

I would be happy to make Custom Providers and get rid of this DigestService if you have a strong preference. The real goal with introducing such a service is to be able to inject them into those parts of Corda that create hashes. See #6440 for an example of what I mean. It makes the `MerkleTree` class use specified hash functions instead of hardcoded SHA-256.

> Also our internal discussions on SecurityManager would make them locked down, where as your approach is bound into the cordapp. I will need to think about the broader design here I think.

I am not aware of those discussion, but I can surely see that it should not be too easy for users to fiddle with the used hash functions. I would be interested to hear more on your design considerations.

**Comment by mvdbos** [comment]
Made obsolete by #6789. Thanks for implementing!

**Pull request closed without merging**
