### PR TITLE
CORDA-3845: Update BC, log4j, slf4j

### PR DESCRIPTION
**Pull request by rnicoll**
* CORDA-3845: Update BC to 1.64
* CORDA-3845: Upgraded log4j to 2.13.3
* We can remove the use of Manifests from the logging package so that when _it_ logs it doesn't error on the fact the stream was already closed by the default Java logger.
* Remove the logging package as a plugin
* latest BC version
* Remove old test
* Fix some rebased changes to log file handling
* Update slf4j too

Co-authored-by: Adel El-Beik <adel.el-beik@r3.com>

### CODE REVIEW

**Review by fowlerrr — DISMISSED** [review]
Looks like all the things that were done for the later versions (with a better explanation in the PR).

**Comment by rnicoll** [comment]
Run tests: slow

**Comment by mnesbit** [comment]
At home I have discovered that log4j2 2.13 does silly things! It seems to repeatedly call down to read the config files from the jars leading to loads of background memory alloc and load when using ASYNC logging. I strongly recommend not updating beyond latest 2.12 version!

**Comment by rnicoll** [comment]
@fowlerrr Please see Matthew's last comment, as I believe we've updated 4.6 to 2.13 as well?

**Comment by fowlerrr** [comment]
> @fowlerrr Please see Matthew's last comment, as I believe we've updated 4.6 to 2.13 as well?

We did: https://github.com/corda/corda/blob/release-os-4.6-RC05/build.gradle#L71

**Comment by rnicoll** [comment]
@fowlerrr I really meant, do we need to downgrade log4j in 4.6 before it ships?

**Comment by fowlerrr** [comment]
@rnicoll It sounds like it might be for the best.  At least until we can do some targeted testing on the concerns

**Comment by mnesbit** [comment]
The conditions in my home project may be different to Corda, but we should attach a profiler to 4.6 and look at byte[] allocations as I found loads of them associated with jar loading and due to log4j2

**Comment by rnicoll** [comment]
@fowlerrr @mnesbit Revised to log4j 2.12.1, please re-review

**Review by fowlerrr — APPROVED** [review]
I think that'll be fine.

**Pull request merged**
