### PR TITLE
NOTICK: Change Corda Version number to 4.3.0

### PR DESCRIPTION
**Pull request by lockathan**
Change Corda version to 4.3.0 since we have now released 4.3

### CODE REVIEW

**Comment by fenryka** [comment]
to be pedantic, this should probably be 4.3.1-snapshot given 4.3 is shipped now

**Review by fenryka — APPROVED** [review]

**Comment by rick-r3** [comment]
what's the theory here?  I could speculate, but... it sounds like we decided to do something that I'm not aware of.

Also, PR title needs to stay in sync.

**Comment by mnesbit** [comment]
I think this will break stuff. We have to stay with 2 digit

**Comment by lockathan** [comment]
Apparently it was decided that we'd adopt a third digit for the release of patches.

**Pull request closed without merging**
