### PR TITLE
CORDA-4100 Configurable ComponentGroup hashing function in WireTransaction

### PR DESCRIPTION
**Pull request by eierina**
Updates to WireTransaction to allow separate hashing function for ComponentGroup MerkleTree leaves vs Merkle Tree nodes/roots.

### CODE REVIEW

**Comment by rekalov** [comment]
My understanding is that we already support different custom hashing functions for ComponentGroup via `DigestAlgorithm.preImageResistantDigest()` and the one for nodes/roots via `DigestAlgorithm.digest()`.
Provided by https://github.com/corda/corda/issues/6844 is fixed.

The only downside is that both need to return the same len, so if it's different, the shorter digest needs to be padded.

Can you doublecheck if it works before going further with this PR?

**Comment by mvdbos** [comment]
> My understanding is that we already support different custom hashing functions for ComponentGroup via `DigestAlgorithm.preImageResistantDigest()` and the one for nodes/roots via `DigestAlgorithm.digest()`.
> Provided by #6844 is fixed.
> 
> The only downside is that both need to return the same len, so if it's different, the shorter digest needs to be padded.
> 
> Can you doublecheck if it works before going further with this PR?

@rekalov @eierina As far as I can see, this is incorrect. Please check my comment on #6849 with explanation: https://github.com/corda/corda/pull/6849#issuecomment-767372347

**Comment by mvdbos** [comment]
Or is it your intention that we create a DigestAlgorithm that actually uses two completely different digest algorithms: one for `DigestAlgorithm.digest()` and another for `DigestAlgorithm.preImageResistantDigest()`? This does not seem intuitive: I would expect one `DigestAlgorithm` extending class to represent, well, one digest algorithm. 

And if that expectation is correct, we do actually need two different `DigestService`s (which are directly delegating to their `DigestAlgorithm`) injected into the `WireTransaction` to be able to set different algorithms for Merkle leaves and nodes, as shown in https://github.com/corda/corda/pull/6849#issuecomment-767372347

**Comment by mvdbos** [comment]
If my expectation is *in*correct, and it is indeed the intention to have one DigestAlgorithm extending class to represent multiple digest algorithms, then perhaps it is an idea to clarify that `DigestAlgorithm.preImageResistantDigest()` will be called *only* for transaction component leaf hashing, just like `DigestAlgorithm.nonceDigest()`is only for transaction component nonces. Either through naming, or through doc comments?

Otherwise, developers might erroneously expect that `DigestAlgorithm.preImageResistantDigest()` simply returns a preimage-resistant version of `DigestAlgorithm.digest()`, where it could unexpectedly be a totally different algorithm.

**Pull request closed without merging**
