### PR TITLE
Add generated code node-schemas

### PR DESCRIPTION
**Pull request by rnicoll**
There is (as of October 2016 at least) no supported option for running Kapt from IntelliJ, which means IntelliJ builds break due to missing classes. This adds in the generated code pending a better solution. Building from Gradle will automatically regenerate the files still, while building from IntelliJ will use the provided defaults.

### CODE REVIEW

**Comment by rnicoll** [comment]
@Clintonio do let me know if I've missed something clever. Did consider having a Gradle task copy the generated files somewhere more useful, but honestly it seems like it just makes it unnecessarily complicated.

**Comment by mikehearn** [comment]
No kapt in intellij? That sounds strange, but there doesn't seem to be much downside in checking in the generated code either.

**Comment by josecoll** [comment]
I'm not a fan of committing generated artefacts (code, docs, etc) but on this occasion perhaps its just a stop gap until IntelliJ provide a hook in their IDE to automatically invoke Kapt as part of the build lifecycle (if project configured to do so).

**Comment by rnicoll** [comment]
Oops, meant to link to the forum that said it's not supported: https://discuss.kotlinlang.org/t/execute-kapt-kapt2-from-within-ij/2006

"This is currently unsupported. What's your use case? Why can't you use Gradle to build your project?"

**Comment by josecoll** [comment]
I've just asked the question in the Slack kotlin #kapt channel (just in case):

Has anyone managed to configure IntelliJ to use Kapt as part of the build lifecycle in a project? (eg. defining Kapt as an Annotation Processor in https://www.jetbrains.com/help/idea/2016.3/annotation-processors.html)

**Comment by Clintonio** [comment]
@rnicoll We could abuse gradle in some way I expect, but this solution is probably cleanest for now. It's in the repo, it's the same for everyone and won't require extra code to be written. One solution would be to start asking _everyone_ to delegate builds to Gradle, which I believe at this point we should.

**Pull request merged**
