### PR TITLE
Allow more arguments to be passed to startTrackedFlow

### PR DESCRIPTION
**Pull request by MrMatthewLayton**
Increased `startTrackedFlow` arg limit from 6 to 12

### CODE REVIEW

**Comment by mnesbit** [comment]
This is a bad idea! They need to wrap their complex parameters into an object.

**Comment by MrMatthewLayton** [comment]
@mnesbit I did think the same thing for _really_ long sets of arguments...is there a general "this is too many" rule in the community that I'm not aware of?

With regards to wrapping into objects though, we did this at TradeIX and I'm trying to steer away from that now, because:

 - It requires mapping code; for example, from the DTO to the _FlowModel_
 - It creates more coupling points between the RPC client and the CorDapp

My personal preference would be that flows should accept _n_ parameters using only types from Kotlin and Corda in order to really decouple layers as much as possible.

See more here: https://github.com/corda/corda/issues/5504

**Comment by mnesbit** [comment]
This approach leaves us at the mercy of compiler changes and isn't able to take advantage of any evolution via carpenter.

**Comment by rnicoll** [comment]
Thanks for the input but this would cause more problems than it resolves.

**Pull request closed without merging**
