### PR TITLE
Feature Request - State Pointer Companion Functions

### PR DESCRIPTION
**Pull request by MrMatthewLayton**
Added companion functions to `StatePointer` to allow easier construction of static and linear pointers.
See: https://github.com/corda/corda/issues/5394

### CODE REVIEW

**Review by roger-that-dev — CHANGES_REQUESTED** [review]
LGTM to me - thanks for the contribution! Do you mind re-raising this PR against the `release/os/4.3` branch? As the procedure we use is to now merge new stuff into the latest release branch.

**Comment by roastario** [comment]
Can one of the admins verify this patch?

**Review by roger-that-dev — COMMENTED** [review]
Looks good to me - needs a rebase though!

**Comment by shamsasari** [comment]
Changes incorporated into https://github.com/corda/corda/pull/5428.

**Pull request closed without merging**
