### PR TITLE
INFRA-347: Corda builds for Windows Servers

### PR DESCRIPTION
**Pull request by wzur-r3**
Configuration for a Jenkins build.

For release branches it starts nightly builds, but for pull requests it start a new build as soon as there is a change in the PR.

### CODE REVIEW

**Review by Schife — COMMENTED** [review]
Maybe we should add the slow integration and smoke tests if this is supposed to be a nightly regression tests against a windows environment?

**Comment by wzur-r3** [comment]
> Maybe we should add the slow integration and smoke tests if this is supposed to be a nightly regression tests against a windows environment?

that may be - for now this configuration is a replication of Teamcity build

**Review by Schife — DISMISSED** [review]

**Review by Schife — DISMISSED** [review]
Looks good

**Review by cairncross — DISMISSED** [review]
LGTM

**Pull request merged**
