### PR TITLE
[CORDA-3298] - Update sql server driver version

### PR DESCRIPTION
**Pull request by dimosr**
Updated the sql server driver to version 6.4, which is the one that works - also verified that via a manual test.

### CODE REVIEW

**Comment by lankydan** [comment]
Are we going to add a comment saying to prefer usage of Postgres for OS? (might be annoying to merge across). Otherwise looks fine to me.

**Comment by dimosr** [comment]
The docs for SQL server already state it's `untested`, I am not sure if we should specifically recommend postgres. 

I don't think there's anything particularly hard about merging, the corresponding ENT docs are completely different, so I'll just resolve the conflict by removing these changes. I was also planning to keep the driver version as-is for ENT, since that's the one that has been tested there.

**Review by lankydan — APPROVED** [review]
Sure, if we are happy with that, then it LGTM.

**Review by JamesHR3 — APPROVED** [review]
LGTM, can update enterprise separately

**Pull request merged**
