### PR TITLE
Size of notary key in vault schema fix.

### PR DESCRIPTION
**Pull request by kasiastreich**
Fix in vault schema so notary_key can have more key entries in CompositeKey, as it's kept as Base58 string. Change default varchar field with size 255 to text.

### CODE REVIEW

**Comment by josecoll** [comment]
Also please can you annotate this PR with other PR related to this change.

**Comment by kasiastreich** [comment]
We don't have currently any upper limit on CompositeKey size. It failed on notary cluster with 5 entries. I can add VARCHAR with size, because I suspect it shouldn't be too big, but @rnicoll should tell more. According to H2 documentation: "CLOB is like VARCHAR, but intended for very large values. Unlike when using VARCHAR, large CLOB objects are not kept fully in-memory; instead, they are streamed. CLOB should be used for documents and texts with arbitrary size such as XML or HTML documents, text files."

As to referring to other PR, that change is independent, because it was coincidence it didn't fail before in our tests.

**Comment by josecoll** [comment]
OK - please can you add a JUnit test in VaultSchemaTest to insert a VaultStateEntity with a large CompositeKey to demonstrate it works.

**Comment by josecoll** [comment]
I've had a quick scan around and I don't think TEXT is a standard type (eg. Oracle doesn't have one) and neither does SQL 92 standard define TEXT: http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt
The requery types are listed here:
http://requery.github.io/javadoc/io/requery/sql/type/package-frame.html
Perhaps it would be better to default to String (which maps to VARCHAR) and specify a reasonably large size.

For example:
```
        @get:Column(name = "note", length = 65536)
        var note: String
```

at run-time generates:
```
INFO: beforeExecuteUpdate stat0 sql:
create table vault_transaction_notes (seq_no integer primary key auto_increment, note varchar(65536), transaction_id varchar(64))
```

**Comment by mikehearn** [comment]
Or we can normalise this and store the known keys in a separate table?

**Comment by josecoll** [comment]
Yes - I have already done this in a separate PR (linear head queries).
But that was before I realised we were storing composite keys.
So perhaps we need to totally de-normalise a Composite Key into its constituents.

**Comment by josecoll** [comment]
Of course I have been having a bit of a nightmare with Requery relationships working as they should. grrrrrrrr.....

```
    @Table(name = "vault_linear_states")
    @Entity(model = "vault")
    interface VaultLinearState : Requery.PersistentState {

        @get:Key
        @get:Generated
        @get:Column(name = "id")
        var id: Int

        /** refers to one or many Anonymous parties who may be able to consume a state in a transaction */
        @get:OneToMany(mappedBy = "key")
        var participants: Set<VaultParty>

        /**
         * [LinearState] attributes
         */

        @get:Index("external_id_index")
        @get:Column(name = "external_id")
        var externalId: String

        @get:Column(name = "uuid", unique = true, nullable = false)
        var uuid: UUID

        /**
         * [DealState] attributes
         */

        @get:Index("deal_reference_index")
        @get:Column(name = "deal_reference")
        var dealRef: String

        @get:OneToMany(mappedBy = "linear_state_parties")
        var dealParties: Set<VaultParty>

        @get:ForeignKey
        @get:OneToOne
        var owner: VaultParty

    }

    @Table(name = "vault_party")
    @Entity(model = "vault")
    interface VaultParty : Persistable  {

        @get:Key
        @get:Generated
        @get:Column(name = "id")
        var id: Int

        // NOTE: remove this back reference when Requery supports Unidirectional relationships
        @get:ManyToOne
        @get:Column(name = "linear_state_parties")
        val linearStateParties: VaultLinearState

        /**
         * [Party] attributes
         */
        @get:Column(name = "party_name")
        var name: String

        @get:Column(name = "party_key")
        var key: String

        // NOTE: remove this back reference when Requery supports Unidirectional relationships
        @get:OneToOne
        val owner: VaultLinearState
    }
```

**Comment by josecoll** [comment]
So please don't let my PR hold this one up!!!

**Comment by kasiastreich** [comment]
Back with change to varchar.

**Pull request merged**
