### PR TITLE
Merge of 4.3 -> 4.4

### PR DESCRIPTION
**Pull request by vkolomeyko**
Technical merge from `4.3` to `4.4` which almost have to take.

Please review your changes to ensure they were merged correctly.

### CODE REVIEW

**Review by zkiss — APPROVED** [review]

**Review by bpaunescu — APPROVED** [review]
My changes look good.

**Review by tudor-malene — APPROVED** [review]
LGTM

**Review by lockathan — APPROVED** [review]
LGTM

**Review by Schife — APPROVED** [review]

**Comment by vkolomeyko** [comment]
I think we do have a quorum in terms of approvals for this PR.
@lockathan - would you be able to do the honours an merge this PR please? (no sqashing/rebasing please)

**Review by edward-prosser — APPROVED** [review]

**Pull request merged**
