### PR TITLE
Add demo for observer node

### PR DESCRIPTION
**Pull request by rnicoll**
Add a demo with an observer node which is required to observe all transactions containing a contract's states, to demonstrate how that can be enforced (i.e. for regulatory requirements).

### CODE REVIEW

**Comment by rnicoll** [comment]
This resurrects the demo from #1918

**Comment by rnicoll** [comment]
@joeldudleyr3 Conclusion on this was that it should be in a different repo, wasn't it?

**Comment by mikehearn** [comment]
Is this PR still relevant? If so, should it be moved out into a separate repo (the IRS demo shows how to use the current support for observers)?

**Comment by rnicoll** [comment]
Closing this, to move it to its own repo instead, as an independent sample

**Pull request closed without merging**
