### PR TITLE
Merge OS4.3 -> OS4.4

### PR DESCRIPTION
**Pull request by roastario**

### CODE REVIEW

**Comment by roastario** [comment]
this is a complicated merge, run smoke tests please

**Comment by roastario** [comment]
run smoke tests please again

**Review by dimosr — APPROVED** [review]
My changes look good.

**Review by chrisr3 — APPROVED** [review]
Just the `@ClassRules` bits? They look OK, although you have _needlessly_ consumed three more lines of the Universe's supply of whitespace :see_no_evil:

**Pull request merged**
