### PR TITLE
Better error message when a legal name clash is found.

### PR DESCRIPTION
**Pull request by joeldudleyr3**

### CODE REVIEW

**Comment by patrickkuo** [comment]
do we see this often? this name duplication should be handled in network map server(hence the reason of the error is not quite right), client shouldn't receive network map with multiple machine having the same name. Something is wrong if we see this in the node. (assuming we are using network map server)

**Comment by joeldudleyr3** [comment]
It is being seen here: https://github.com/corda/corda/issues/2984.

**Comment by patrickkuo** [comment]
so the reason for the error in #2984 is keystore was tempered/changed, maybe it's more useful to print out the the node infos(CN and public key)

**Comment by joeldudleyr3** [comment]
Can you provide an example? Not sure what you mean.

**Comment by patrickkuo** [comment]
maybe something like: "More than one node found with legal name $name. NodeInfos: $nodeInfos"

the root cause of the problem is in the addNode method. We checks for public key when adding node, where we should also check the name.  We need a bug jira to rectify this.

**Comment by joeldudleyr3** [comment]
@patrickkuo @mnesbit Thank you both. I’ll close this and split it into individual bug JIRAs.

**Pull request closed without merging**
