### PR TITLE
Correct handling of trying to record state more than once

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by josecoll** [comment]
Will defer to @mnesbit and @mikehearn as I don't fully understand the background leading to these changes.

**Comment by rnicoll** [comment]
To try explaining for future reference:

1. Node A generates a transaction X
2. Node A generates two further transactions, Y & Z, which take states from X as inputs.
3. Node A sends transactions Y & Z to node B
4. Node B's receive transaction flows both request transaction X.
5. Node A sends two copies of transaction X (one for each request) to node B.
6. Node B tries to double-record transaction X, and the database errors due to primary key conflict.

**Comment by mikehearn** [comment]
I think your writeup must be missing some crucial detail here. I can see that this would be a problem if, in step 3, that's "Node A sends Y and Z to node B *in parallel flows*". Is that correct?

**Comment by mikehearn** [comment]
Also shouldn't the fix be to detect a duplicate add attempt before the data goes to the vault at all?

**Comment by rnicoll** [comment]
Certainly there's parallel flows being triggered within `ScheduledFlowTests`, although it's been pointed out they shouldn't be interacting.

There's always going to be some risk of trying to save a duplicate transaction when we scale up number of flows, as there will be a window between checking if we have a transaction and receiving a copy, and the only practical way to atomically write a transaction out only if we don't have it already is to have the database handle it.

With Matthew's help we have gone through the code and confirmed that `FetchTransactionsFlow` (which `ResolveTransactionsFlow` subflows to) is checking if it has transactions before trying to retrieve them, at least.

**Comment by mikehearn** [comment]
I don't get why the vault code is changing here. Transaction X is not something that was sent to node B for any reason other than dependency resolution, right? And redundant adds to validated tx set are already ignored, I thought?

**Pull request merged**
