### PR TITLE
ENT-2100 quick start page to include user journeys

### PR DESCRIPTION
**Pull request by GavT**
Updated the quick start guide to provide links based on a visitors user journey which is assumed to be one of:
Develop a CorDapp
Test a CorDapp
Build a demo Corda network locally
Add a node to an existing Dev or Test network
Add a node to an existing Production network 

screen shot 2018-07-05 at 16 16 19

### CODE REVIEW

**Comment by tlil** [comment]
@GavT is this essentially the same as this ticket? https://r3-cev.atlassian.net/browse/ENT-2092 cc @anvabr

**Comment by GavT** [comment]
Yes @tlil good spot

**Comment by tlil** [comment]
Added a screenshot of the rendering to the PR description.

To reduce the cognitive load on the reader, perhaps worth breaking it down so that first, he/she sees the 5 main headlines "Develop ...", "Test ...", etc., then, next step (when having selected main category), present the suboptions...?

**Comment by GavT** [comment]
@tlil does that mean having collapsing tables / expanding lists? How do you do that in rst? Or have I misunderstood? I do want all this to live on one page

**Comment by tlil** [comment]
I mean essentially having those 5 steps as links at the top, linking to sections further down on the page. Or something like that  .

**Comment by tlil** [comment]
I just fear the table in its current form is a bit too much too take in; in shear size and granularity.

**Comment by GavT** [comment]
@joeldudleyr3 can you build this and check out the ref links please

**Comment by tlil** [comment]
image

**Comment by tlil** [comment]
Could potentially loose the TOC at the top actually. Due to the page length, it doesn't really do much :)

**Comment by joeldudleyr3** [comment]
@GavT Based on Tommy's screenshot, you need to add headers for tables 3-5. Also, it looks weird that the link to the production table isn't the first word of the sentence. It's not a problem that the word "Add" is used twice. The word the user sees can be different to the reference header.

**Comment by GavT** [comment]
@joeldudleyr3 fixed table headers and production link
@tlil gonna leave the TOC in ;-)

**Comment by joeldudleyr3** [comment]
The bottom three tables are gone for me now:

screen shot 2018-07-09 at 11 55 12

**Comment by GavT** [comment]
image

**Pull request merged**
