### PR TITLE
Bank of Corda demo: Fix broken RPC client test.

### PR DESCRIPTION
**Pull request by fracting**

### CODE REVIEW

**Comment by fracting** [comment]
I can't find any entry to read the CI report, but it seems to hang for unreasonable time? The test case passed on my local machine, anyone give some hints?

**Comment by mikehearn** [comment]
Yes, CI is slow, there's often a backlog if lots of code is uploaded at once. I've assigned Jose to review this.

**Comment by mikehearn** [comment]
Thanks Qian, can you please state clearly that you're in compliance with the developer certificate of origin (see CONTRIBUTING.md) - just saying "I have read CONTRIBUTING.md and am in compliance" is sufficient. It mostly just means that your employer won't suddenly pipe up and say you weren't allowed to contribute that.

And hey, it's nice to encounter another CodeWeaver! :) 

http://marc.info/?a=107705377400001&r=1&w=2

**Comment by fracting** [comment]
@josecoll Thanks for reviewing!

I have read CONTRIBUTING.md and am in compliance.

@mikehearn Glad to join! :)

**Comment by fracting** [comment]
BTW, would you like to consider using CLA assistant for the developer certificate and permission?

https://cla-assistant.io/

Example like this: https://github.com/drone/drone/pull/1966#issuecomment-286940303

Let me know if there is anything I can help :)

**Comment by mikehearn** [comment]
Thanks for the link to CLA assistant - it looks interesting, we'll check it out.

**Pull request merged**
