### PR TITLE
[EG-503] Spent state audit tool

### PR DESCRIPTION
**Pull request by relyafi**
Open core changes required to facilitate the spent state audit tool functionality delivered in ENT. No functional impact on OS.

### CODE REVIEW

**Comment by mnesbit** [comment]
Why on earth are these public flows in core? Surely this exposes a whole load of information leakage problems and possibly make denial-of-state problems worse. I can understand wanting a locally queryable flow to aid monitoring, but this is unclear.

**Comment by relyafi** [comment]
> Why on earth are these public flows in core? Surely this exposes a whole load of information leakage problems and possibly make denial-of-state problems worse. I can understand wanting a locally queryable flow to aid monitoring, but this is unclear.

The flows are read-only, and can currently only be invoked on a notary, because the flows are only installed on a node configured as a notary, and are hard coded to not talk to an external system.  The "client" flow is additionally not annotated with InitiatedBy to stop custom flows from talking to it.

**Comment by relyafi** [comment]
@mnesbit This change has been updated to integrate @vkolomeyko 's work to use the extensions API. Flow logic has been removed as a result and the remaining OS changes simplified.

**Review by vkolomeyko — APPROVED** [review]

**Comment by vkolomeyko** [comment]
We have also used this `core` code in ENT and reasonably sure that these changes will be enough to complete EG-503 in ENT.

**Review by mnesbit — APPROVED** [review]
OK

**Review by thschroeter — APPROVED** [review]
LGTM

**Pull request merged**
