### PR TITLE
INFRA-284 Testing out new aks template

### PR DESCRIPTION
**Pull request by Schife**
Switching the label on jenkinsfiles to test out the new aks cluster

### CODE REVIEW

**Comment by Schife** [comment]
run tests: unit

**Review by wzur-r3 — APPROVED** [review]
LGTM - AKS cluster is back in action

**Comment by Schife** [comment]
run tests: integration

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: slow

**Comment by Schife** [comment]
run tests: slow

**Pull request merged**
