### PR TITLE
[CORDA-3304] Introduce max number of retries per invocation for recon…

### PR DESCRIPTION
**Pull request by dimosr**
### Changes
This change introduces a max. number of retries per invoked RPC call. This is also a defense against permanent failures, e.g. configuration errors.

### Testing
Tested manually by simluating a scenario where the client throws the same exception always, making sure max number of retries is respected, since this it not easy to simulate in an automated way atm.

### CODE REVIEW

**Review by fowlerrr — COMMENTED** [review]
Looks okay.  Probably removes the need to https://github.com/corda/corda/pull/5558.

Could you add some docs and test cross version compatibility?  Both new RPC against old server and old RPC against new server.

**Comment by dimosr** [comment]
Added a small update to the docs for the new field. As discussed offline, the other issue still needs to be worked on. I did a small test with different versions, but I think we are OK anyway, since this change is only client-side, so it does not involve client/server interaction.

**Review by fowlerrr — DISMISSED** [review]
Looks good

**Review by fowlerrr — APPROVED** [review]
Last changes look good too.

**Pull request merged**
