### PR TITLE
extract only the last class in path for adding to transaction

### PR DESCRIPTION
**Pull request by roastario**

### CODE REVIEW

**Review by tudor-malene — COMMENTED** [review]
I would like us to replicate the exception before deciding how to fix it.
Maybe this is the right approach, or maybe just getting the "caused by" exception.

**Comment by shamsasari** [comment]
I believe this is superseded by https://github.com/corda/corda/pull/5046?

**Comment by tudor-malene** [comment]
> I believe this is superseded by #5046?

Possibly. 
This is handling a different use case when the `NoClassDefFound` is thrown using some custom error message which contains the class name.

If we could replicate the issue, we would know if it got fixed #5046 or we need the regex approach

**Comment by roastario** [comment]
addressed by tudor's proper fix.

**Pull request closed without merging**
