### PR TITLE
Initial stub for IntelliJ Code Style settings

### PR DESCRIPTION
**Pull request by vkolomeyko**

### CODE REVIEW

**Comment by mkit** [comment]
Don't we need .gitignore update as well for this?

**Comment by vkolomeyko** [comment]
I do not think we need to fiddle with `.gitignore` as it only prevents *adding* files to Git.
Once the file is added (I had to run: `git add -f`) it can be version controlled just like any other file.

**Comment by mikehearn** [comment]
If you do a reformatting run with these settings, does it cause a lot of churn?

**Comment by vkolomeyko** [comment]
Without imports optimisation enabled - 463 files in the whole Corda codebase.
Changes are mainly around managing rogue spaces to make code look consistent.

**Comment by tlil** [comment]
@mikehearn see [here](https://github.com/corda/corda/compare/tlil/reformat-2017-oct?expand=1) for a snapshot of the output using the current settings.

**Pull request merged**
