### PR TITLE
Moved Driver.kt to net.corda.testing.driver in the test-utils module

### PR DESCRIPTION
**Pull request by shamsasari**

### CODE REVIEW

**Comment by shamsasari** [comment]
Yes, I thinking it might be better to do the move first.

With regards to the demos, what else should it be if not compile dependency on test-utils?

**Comment by exFalso** [comment]
Imho the driver Main.kts should be under `test` rather than in `main`, then we can move the `test-utils` dependency from `compile` to `testCompile`.

The reason I think we should do it like this is because API users will likely copy the demo code structure, which means they will bloat their cordapp dependencies with `test-utils` (`test-utils` depends on everything)

**Comment by shamsasari** [comment]
Hmm, it's not typical to have `main` in `test` - I wonder if that will trip people up somehow. But yeah, I don't like how the demos pull everything in due to the driver - I saw this with Roger's oracle example and this PR doesn't really fix that. Is test-utils where the Driver should go? Should we put it into its own module?

**Comment by shamsasari** [comment]
I'll try your suggestion on moving the `main` methods to test

**Comment by shamsasari** [comment]
Demo's which make use of the driver in a `main` method have had that `main` method moved to test. This allows the `test-utils` dependency to these "CorDapps" to be testCompile rather than compile.

**Comment by shamsasari** [comment]
I'll move the main methods to test in a separate PR. Back to @exFalso.

**Pull request merged**
