### PR TITLE
ENT-5263: Backport CORDA-3662: Use an INNER JOIN for network map cache queries

### PR DESCRIPTION
**Pull request by fowlerrr**
Backport from 4.5:

- rename add or update function for clarity
- put removal of old nodes after retrieval of new ones to avoid gaps in the map
- plus add a test

### CODE REVIEW

**Comment by rick-r3** [comment]
This wasn't the distinct that doesn't work on Postgres though, was it?

**Comment by fowlerrr** [comment]
> This wasn't the distinct that doesn't work on Postgres though, was it?

Exactly that one.  Shall I backport that change as well?

**Comment by rick-r3** [comment]
I would think so.

**Review by josephzunigadaly — APPROVED** [review]

**Comment by rick-r3** [comment]
I will not squash seeing as two bug fixes.

**Comment by rick-r3** [comment]
merged as two commits

**Pull request merged**
