### PR TITLE
Add unit tests around vault update derivation

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by josecoll** [comment]
I thought we were getting rid of relevancy checks. Therefore, why bother refactoring code and adding Unit tests for this?

**Comment by rnicoll** [comment]
I'd like to get rid of the checks, but it's by no means a decision made, let alone something we know when would happen.

**Comment by josecoll** [comment]
@mikehearn please can you confirm that we will be removing the relevancy check before V1.0 (and hence invalidating this refactoring effort).

**Comment by mikehearn** [comment]
Yes, that's the goal - it's waiting on Patrick's PR #964 

However, if this PR works (and it seems to) then we lose nothing by merging it now it's written - it's perhaps a communication issue on my side that I didn't communicate the plan for removing isRelevant very well. For now let's just merge this and hope it all goes according to plan and we can remove it again shortly.

**Pull request merged**
