### PR TITLE
Renamed TransactionKeyFlow to SwapIdentitiesFlow and made it an inlin…

### PR DESCRIPTION
**Pull request by shamsasari**
…e flow.

This required some tweaking to the existing cash flows.

TransactionKeyFlow needs to be an inline flow as otherwise anyone can spam a node for anonymous identities. Now only the relevant parties in a transaction can ask for the other side's anonymous identity.

### CODE REVIEW

**Comment by rnicoll** [comment]
I like the general direction, but `IssuerFlow` can't be used this way, it's (as per docs at the top of the class) for testing only. It essentially accepts arbitrary issuance requests and fulfils them blindly without in any way asking why it should hand money to the requester.

I'm going to try ripping `IssuerFlow` out before it causes any more confusion (I worry that people will miss the warning on the top and use it in production), as we're down to one sample that uses it. Can you raise the rename as its own PR as I think that's easy to get in quickly, and I'll then come back to this.

**Comment by shamsasari** [comment]
This PR doesn't change the way `IssuerFlow` works. It still accepts issuance requests and fulfils them blindly. What bit do you think has changed?

**Comment by shamsasari** [comment]
This isn't just a simple rename. Making the flow inline affects how it's used in the cash flows. I see that you've raised #1226 to remove the `IssuerFlow`. I'm blocked by that as I need to know how you've changed the cash flows.

**Comment by mnesbit** [comment]
Where is this at? Does this need handing over/deleting?

**Comment by rnicoll** [comment]
Can this be rebased off #1230 perhaps? Although I need to finish that PR

**Comment by shamsasari** [comment]
I've rebased and scaled back my changes. The only changes now are that `TransactionKeyFlow` is renamed to `SwapIdentitiesFlow` and that it's been inlined. The existing cash flows are untouched, except for `CashPaymentFlow` where the anonymisation bit is commented out and I've added a TODO on two possible solutions on how to proceed.

**Comment by rnicoll** [comment]
I'd like to rebase this off #1230 which gives us points at which the `SwapIdentitiesFlow` can be triggered from the payment fow. I'll tackle that next week when I'm back, if that's okay?

**Comment by shamsasari** [comment]
Closing for now.

**Pull request closed without merging**
