### PR TITLE
Removed NonEmptySet

### PR DESCRIPTION
**Pull request by shamsasari**
Removing this as it's only used in the finance module and so hasn't really had much uptake. As part of stabilising our utility classes, it doesn't make sense to keep this and tie ourselves down in maintaining it.

### CODE REVIEW

**Comment by rnicoll** [comment]
Happy with this

@mikehearn you asked for this class, wanted to check you're okay too.

**Comment by shamsasari** [comment]
I actually like the idea of `NonEmptySet` and `NonEmptyList` so I'm OK with abandoning this PR if we think this is worth having.

**Comment by mikehearn** [comment]
Well, it seems useful - it may be that we just aren't using it as much as we should. How about we just move it into node instead and we can go ahead and see if there are places we should be using it later.

**Comment by shamsasari** [comment]
Instead what I'll do is add a TODO to investigate further uses of it, possibly also including NonEmptyList.

**Pull request closed without merging**
