### PR TITLE
CORDA-2767: Add missing cliutils dependency to explorer

### PR DESCRIPTION
**Pull request by cburlinchon**

### CODE REVIEW

**Comment by anthonykeenan** [comment]
Can you change it to a public Jira please!

**Comment by cburlinchon** [comment]
I removed the copying of log4j file from config/dev, we seem to do this in other places, https://r3-cev.atlassian.net/browse/CORDA-2768

**Comment by cburlinchon** [comment]
> Does that cause the error to go away?

Yep as we no longer bundle the config/dev/log4j which has ErrorCodeRewritePolicy

**Comment by anthonykeenan** [comment]
Does that not mean it just doesn't do any logging at all now?

**Comment by cburlinchon** [comment]
> Does that not mean it just doesn't do any logging at all now?

no it logs, it picks up the log4j file from explorer, which makes more sense

**Pull request merged**
