### PR TITLE
NOTICK OS 4.5 to 4.6 merge 2020-07-08

### PR DESCRIPTION
**Pull request by lankydan**

### CODE REVIEW

**Comment by lankydan** [comment]
Run tests: slow

**Comment by lankydan** [comment]
@rick-r3 Can you look at `TopLevelTransition` as I have added code to get the merged in changes to work in 4.6.

**Review by Schife — APPROVED** [review]
Infra changes look good

**Review by chrisr3 — APPROVED** [review]
My changes look OK.

**Review by rick-r3 — APPROVED** [review]

**Pull request merged**
