### PR TITLE
NOTICK - OS 4.6 to OS 4.7 merge 20200814

### PR DESCRIPTION
**Pull request by nikinagy**
OS 4.6 to OS 4.7 merge

### CODE REVIEW

**Comment by chrisr3** [comment]
run tests: smoke, slow

**Review by woggioni — DISMISSED** [review]

**Review by vkolomeyko — DISMISSED** [review]

**Review by roastario — APPROVED** [review]

**Review by yift-r3 — COMMENTED** [review]
LGTM

**Review by filipesoliveira — APPROVED** [review]

**Review by kyriathar — APPROVED** [review]
merging of [CORDA-3882](https://r3-cev.atlassian.net/browse/CORDA-3882) looks good.

**Review by rnicoll — APPROVED** [review]

**Review by mnesbit — APPROVED** [review]
OK

**Pull request merged**
