### PR TITLE
 Claim agent's port before attempting to open it

### PR DESCRIPTION
**Pull request by andr3ej**

### CODE REVIEW

**Comment by exFalso** [comment]
If this is to avoid port clashes between tests then I think we could use the check done by `addressMustNotBeBoundFuture` instead of poking the filesystem. That will also work for inter-test-run lingering bound ports

**Comment by andr3ej** [comment]
is it safe to assume the gradle processes never overlap?

**Comment by exFalso** [comment]
they do overlap (in terms of port pools), from what i understand gradle spawns a new process for each test task

**Comment by andr3ej** [comment]
the advantage of this solution is it works even if Gradle Test Executor processes run concurrently. but i've now done a test and it looks like they run one at a time, so addressMustNotBeBoundFuture is sufficient. do you want to implement that in your pr or shall i change this one?

**Comment by exFalso** [comment]
Perhaps change this one, this includes the parent dir traversal fix

**Comment by exFalso** [comment]
@andr3ej is this still relevant?

**Comment by andr3ej** [comment]
now that things are sort of working again, i feel like this change may hide new problems, so closing

**Pull request closed without merging**
