### PR TITLE
CORDA-1711 - Remove dependency on PathUtilsKt in net.corda.core.internal

### PR DESCRIPTION
**Pull request by tlil**
https://github.com/corda/corda/pull/3493
https://github.com/corda/enterprise/pull/1141

### CODE REVIEW

**Comment by anthonykeenan** [comment]
Should it not go into O/S master first?

**Comment by fenryka** [comment]
@tlil can we move the ENT project bug to Corda then redo this commit? all issues in Corda should have Corda bugs

**Comment by fenryka** [comment]
@anthonykeenan also raises a good point

**Comment by tlil** [comment]
Yep x 2, duh, my bad.

**Comment by tlil** [comment]
@anthonykeenan @fenryka  ENT ticket moved to CORDA-1711, and PR raised against `master` as well (https://github.com/corda/corda/pull/3493), cherry-picked across to the release branch (here).

**Pull request merged**
