### PR TITLE
Adds the cheat sheet to the docsite.

### PR DESCRIPTION
**Pull request by joeldudleyr3**

### CODE REVIEW

**Comment by mikehearn** [comment]
Shouldn't this be linked to from some other page, I mean does it really justify an entire page to itself? Alternatively could you render it to a JPEG and check in the rendered copy, with the PDF available via a link as now?

**Comment by roger3cev** [comment]
Which page would you suggest @mikehearn ? Cheers

**Comment by mikehearn** [comment]
No particular suggestions. It just seems weird to have a page that consists of a single sentence.

**Comment by roger3cev** [comment]
LGTM - will refactor this page into a geeneral quick start/help page as part of the impending docsite re-organisation.

**Pull request merged**
