### PR TITLE
Add quasar-hook agent for inspecting quasar instrumentation

### PR DESCRIPTION
**Pull request by exFalso**
This PR adds a little tool to calculate the exclude pattern to be used with quasar in order to stop it from scanning everything.

See https://github.com/puniverse/quasar/issues/243 for details on the exclude feature.

I also added an `@Ignore`d test that measures startup time of nodes, the exclude pattern more than halves startup time.

Note however that this feature is not yet released in quasar. I added commented out code that adds the pattern to the relevant parts of the code. To be uncommented once they release 0.7.8 and we upgrade.

Also please note that this is an internal tool, so the code isn't pretty at times, just wanted to write something working quickly.

### CODE REVIEW

**Comment by mikehearn** [comment]
Just check it into experimental. It doesn't need to be reviewed. I'm not convinced this approach makes sense anyway - why not just fork quasar itself? An agent instrumenting another agent is a bizarre way to do things when the source is available!

**Comment by exFalso** [comment]
Hmm I wanted it to be completely separate in order to be less intrusive and avoid having to do the fork dance. This way we can use the original quasar agent and add our own agent on top if we want to inspect what it's doing, and just not add it if we want the full behaviour.

**Comment by mikehearn** [comment]
jitpack.io makes forking projects a ton easier than it used to be - you just use the github fork button (assuming upstream is on github), commit your changes, then change the name of the dependency in gradle. When the HTTP request for the download arrives, jitpack checks out the git repository, compiles it, takes the artifacts and inserts them into its own Maven repository, and then serves it back to you! It's hard to make it simpler than that!

**Comment by exFalso** [comment]
Ok, makes sense. We may have to play around with quasar later anyway. I'll move this into experimental for now as-is and move onto other stuff, should be fairly easy to port this into a fork next time we want to touch quasar.

**Comment by mikehearn** [comment]
great

**Pull request merged**
