### PR TITLE
Rename notary flows

### PR DESCRIPTION
**Pull request by adagys**
A proposal to rename `NotaryFlow.Client` -> `NotarisationFlow`, and `NotaryFlow.Service` -> `NotarisationHandler`. `NotaryFlow.Client` shouldn't be used by CorDapps directly, since we have `FinalityFlow` (?), so I think it's a low impact breaking change.

### CODE REVIEW

**Comment by mikehearn** [comment]
What's the rationale for the rename?

**Comment by adagys** [comment]
`NotarisationHandler` falls in line with our new naming convention for "service" flows that respond to requests. It then no longer make sense to have `NotaryFlow.Client`, and I think `NotarisationFlow` makes it more clear what it does.

**Comment by mikehearn** [comment]
OK, I wasn't aware of any new naming convention. Is it documented anywhere? If not, can we get a PR to change the docsite to tell developers about the convention before adjusting things?

**Comment by mikehearn** [comment]
What's happening with this PR? Is it still being worked on?

**Comment by adagys** [comment]
I'll shelve it for now, as it will create a lot of needless conflicts. Will re-do when there's less code churn

**Pull request closed without merging**
