### PR TITLE
Stricter Driver shutdown

### PR DESCRIPTION
**Pull request by andr3ej**
* Blow up instead of hanging so we don't hog the TC agent
* Log if shutdown took suspiciously long, so we can blame / rule it out as a cause of slow builds

### CODE REVIEW

**Comment by mikehearn** [comment]
This PR doesn't seem to have a reviewer any more - is it intentional? I can bug Clinton to look at it once it starts passing TC.

**Comment by andr3ej** [comment]
It is intentional - I was surprised that this detects a thread leak in the network map registration test so I've removed him while I try to make the test non-leaky.

**Comment by mikehearn** [comment]
Should we close this PR until it's ready for review?

**Comment by andr3ej** [comment]
Yeah OK. This has highlighted one or two Artemis shutdown problems that need to be fixed first.

**Pull request closed without merging**
