### PR TITLE
Added initialise method to CordaPluginRegistry which removes the need…

### PR DESCRIPTION
**Pull request by shamsasari**
… for plugin services

### CODE REVIEW

**Comment by mikehearn** [comment]
Can you update the changelog section of the docsite too, to guide devs through the upgrade.

**Comment by mikehearn** [comment]
Thinking about it, whilst this is a nice cleanup, the direction I'd like us to go here is by using annotations a la Spring, rather than having a single app-specific class. It can be done easily using the reflections library:

https://github.com/ronmamo/reflections

Having to create a special class, then put its name in a special file with an awkward name, is not as nice as just sticking `@Flow @StartableByPeers` or `@Plugin` or whatever at the top of your class.

**Comment by shamsasari** [comment]
Yes the service loading has to go, and I assumed as such in my versioning design doc, without explicitly mentioning it. Perhaps this PR is not worth it and I should do that first. I'll think about this more.

**Comment by mikehearn** [comment]
I'm OK with merging it but it'd need docsite updates and the like, and then the tutorial/template apps etc, so it's getting to be a fair bit of work to change the API. We shouldn't plan to change each thing more than once.

**Comment by mnesbit** [comment]
I looked at class scanning originally. Node startup was horrible i.e. > 60 seconds of scanning! The ServiceLoader is not very logical, but it does run at a sensible speed.

**Comment by mikehearn** [comment]
Yeah, I wonder how Spring makes it fast enough. We could take a look. I suspect brute-force byte-string matching would work surprisingly well as a fast first-pass filter along with hash->classmap caching.

**Comment by chrisr3** [comment]
I believe CDI/WELD scan for annotated classes using [Jandex](https://github.com/wildfly/jandex).

**Comment by shamsasari** [comment]
This PR is not worth the effort of updating the docs and providing an upgrade path, considering this is not the end goal. Closing...

**Pull request closed without merging**
