### PR TITLE
CORDA-3024 Rename the webserver

### PR DESCRIPTION
**Pull request by tudor-malene**
see https://r3-cev.atlassian.net/browse/CORDA-3024

This moves the webserver project into the testing folder and renames the artifact.

I've tested `deployNodes`, driver tests with `startWebserver` and the demobench, and they all work.

### CODE REVIEW

**Review by chrisr3 — COMMENTED** [review]
Looks reasonable, from a Gradle perspecrive. Although I'd like to see the build succeed first :wink:.

**Comment by tudor-malene** [comment]
@chrisr3 , the build passed.

**Review by roastario — DISMISSED** [review]
LGTM

**Review by chrisr3 — DISMISSED** [review]
If it works with DemoBench then it _must_ be OK :wink:.

**Review by shamsasari — CHANGES_REQUESTED** [review]
The changelog needs to be updated

**Comment by tudor-malene** [comment]
back to you @shamsasari

**Review by shamsasari — APPROVED** [review]
Thanks

**Pull request merged**
