### PR TITLE
Fix incorrect port numbers in documentation for node explorer

### PR DESCRIPTION
**Pull request by gary-rowe**
The current documentation incorrectly identifies the port numbers when running up the node explorer. This can lead to confusion as developers use the documentation over the log messages and fail to connect to the nodes.

### CODE REVIEW

**Comment by mikehearn** [comment]
Whoops, thanks!

**Comment by mikehearn** [comment]
I suspect it's not legally necessary in this case as facts/typo fixes can't be copyrighted, but we may as well get it out of the way. Can you pinky-swear hope-to-die that you have read the CONTRIBUTING.md file and can agree in writing that you're legally authorised to make this contribution? Then we can merge away.

**Comment by gary-rowe** [comment]
@mikehearn No problem. I pinky-swear that I have read the CONTRIBUTING.md document and I am in a position to offer up this work as a private individual.

**Comment by mikehearn** [comment]
👍

**Pull request merged**
