### PR TITLE
Make RPCClient use a durable Artemis queue (instead of a temporary one)

### PR DESCRIPTION
**Pull request by adagys**
This fixes the randomly hanging integration test in `RPCStabilityTests`.

With temporary queues, when the server restarts, the client is sometimes not able to recreate its queue in time, so the server is unable to send back a response message and just drops it, causing the client to hang.
I filed a bug with Artemis, but it seems like that is normal behaviour. The alternative solution is to use a single session in `RPCProxyHandler` for both producer and consumer, but my understanding is that we'd lose performance this way ( @exFalso ?)

### CODE REVIEW

**Comment by mikehearn** [comment]
It uses non-durable queues deliberately. I don't think you want a durable queue for RPC. There's an expectation that if you kill an RPC client, outstanding state is wiped and you can restart it to get a clean start. Durable queues would break that. They'd also cause resource leaks because if an RPC client died its queue would never get cleaned up.

There is for sure a better way to fix shutdown hangs. If the server-side session has been terminated due to timeout and the queue is gone, the client should detect that and forcibly close the proxy, throwing an exception

**Comment by adagys** [comment]
The issue is not really a shutdown hang, it's when we have the RPC client doing a request right after the server has restarted (the client auto-reconnection is managed by Artemis). The server receives the request and tries to send a response to the client queue, but its bindings aren't set yet, and the response gets dropped. So the client is just left waiting for a response.

I do agree that using durable queues is undesirable though.

**Comment by mikehearn** [comment]
So it's a startup race in the broker itself? Or in RPC connection establishment?

**Comment by adagys** [comment]
Well, it's an Artemis race. The RPC client uses different Artemis sessions for producers and the consumer. The sessions support automatic failover once they detect the the broker is down. Since the server queue is durable, it's immediately available on broker restart, so the client producer session gets re-established instantly and is able to send messages. Meanwhile, the consumer session tries to failover and recreate the consumer, which in turn instructs the server to recreate the temporary client queue. But while the client queue is being created the RPC client is able to send messages to the server queue, but the server cannot send any response.

**Comment by adagys** [comment]
Another solution would be creating a client consumer+queue for every client producer, which might be a better approach.

**Comment by mikehearn** [comment]
None of the queues involved with RPC are meant to be durable, which do you mean by "server queue"?

It sounds like the right fix is to either use the same session for producer and consumer, or to block the RPC client inside send if the consumer isn't ready yet.

**Comment by exFalso** [comment]
> or to block the RPC client inside send if the consumer isn't ready yet.

The consumer *is* ready at this point, the session failover is transparent, but the underlying queue failover is racy.

I think the proper solution for this is to introduce some additional state into the RPC server to buffer messages until the binding is created. Similarly to how we listen on removed client bindings we can use Artemis notifications to do this. The state should then be cleaned up on binding removal (say in `invalidateClient`)

**Comment by adagys** [comment]
So I guess we could add a failover listener on the consumer session that will pause producers, and then wait for a "binding added" notification message to resume them. Although I'm slightly wary of making the RPC mechanism even more complex.. This might also lead to even more obscure race conditions where the producer sessions might finish failover before the consumer session starts it, so we might need to listen and start buffering on any session failover..

**Comment by mikehearn** [comment]
Yeah, the failover listener sounds like the right way to go here?

**Pull request closed without merging**
