### PR TITLE
INFRA-563: Update Corda to test distributed-testing-plugin 1.3-SNAPSHOT.

### PR DESCRIPTION
**Pull request by chrisr3**
Update Corda to use DSL for distributed-testing-plugin-1.3-SNAPSHOT.

### CODE REVIEW

**Comment by chrisr3** [comment]
run tests: smoke slow

**Comment by chrisr3** [comment]
run tests: slow

**Comment by chrisr3** [comment]
run tests: slow

**Comment by chrisr3** [comment]
run tests: smoke, slow

**Comment by chrisr3** [comment]
run tests: smoke, slow

**Comment by chrisr3** [comment]
run tests: smoke, slow

**Comment by chrisr3** [comment]
run tests: smoke, slow

**Review by rnicoll — APPROVED** [review]

**Pull request merged**
