### PR TITLE
Updated repository lists to reduce dependency on Jitpack and removed …

### PR DESCRIPTION
**Pull request by adagys**
…unused repositories.

This fixes the problem with the broken bft-smart dependency

### CODE REVIEW

**Comment by opticyclic** [comment]
How does this reduce the dependency on jitpack? You haven't removed jitpack from the repository list.

**Comment by Clintonio** [comment]
(Or whoever is currently release managing V3). 

Also the branch needs some changes. The Artifactory context URL variable isn't in the V3 build.gradles it seems.

**Comment by opticyclic** [comment]
So if there is a corrupt dependency in jitpack wont this propagate down to when people use corda as a dependency?

**Comment by fenryka** [comment]
Seems acceptable to me, this won't impact users I assume

**Comment by opticyclic** [comment]
All this has done is hide the issue internally at R3 but it still exists for all the clients.

**Comment by mikehearn** [comment]
Yes, we are sending some instructions to corda-dev and I'm asking JitPack support if they can restore the package. We've added the package to our own artifactory but beyond distributing instructions and trying to get jitpack fixed, I'm not sure there's much more we can do - Maven/Gradle type build systems assume repositories are immutable and it seems to be a bug in jitpack that it's not.

**Pull request merged**
