### PR TITLE
Change party equality conditions

### PR DESCRIPTION
**Pull request by rnicoll**
This changes the conditions under which parties are considered equivalent, to:

* For `Party` and `Party`; comparison on name
* For `AnonymousParty` and `AnonymousParty`; comparison on key
* For `Party` and `AnonymousParty`; never equal

This is so that for full parties, they're equivalent if the underlying identity is the same, and for anonymous parties they're equal if the keys match (which is really only so they can be used in maps and sets).

### CODE REVIEW

**Comment by mnesbit** [comment]
I strongly dislike the idea of this! Equality must operate as people expect, this will be chaos. It will be non-transitive. It won't be clear how to hash them into a mixed collection. It will be chaos.

**Comment by chrisr3** [comment]
As one of my RPC "smoke tests", I executed the following against a `DUMMY_NOTARY` node. And it fails, saying that `nodeInfo[0].legalIdentity != DUMMY_NOTARY`.

```kotlin
@Test
fun `test network map`() {
    val (nodeInfo, updates) = rpcProxy.networkMapUpdates()
    updates.notUsed()
    assertEquals(1, nodeInfo.size)
    assertEquals(DUMMY_NOTARY, nodeInfo[0].legalIdentity)
}
```
So my question is: Is the above test reasonable?

**Comment by mnesbit** [comment]
As discussed, this is more an artifact of the node being a freshly instantiated corda.jar node, which manufactures a new key. It isn't really a fair test. Our comparisons should happen in contexts where the node has already got a stable identity.

**Comment by rnicoll** [comment]
Okay, sounds like we're happy with `Party` equality working on the key, and name based is a special case. Closing now.

**Pull request closed without merging**
