### PR TITLE
CORDA-3697 - making sure hibernate uses UTC time zone

### PR DESCRIPTION
**Pull request by nikinagy**
Making Hibernate to use UTC time zone for database entries.

### CODE REVIEW

**Comment by rick-r3** [comment]
Are you able to describe some of the scenarios this fixes, or that you have tested it with?  e.g. did you change the time zone of the node and/or database servers etc ?

**Comment by nikinagy** [comment]
I wrote a test for it, but in OS we don't have IntegrationTest.kt which was used for it, so after discussing it with Matthew we decided to merge the test only to the enterprise versions.
I also did some 'manual' testing with docker Postgres db, checked the db manually after a node started a flow.

**Comment by mnesbit** [comment]
We should ensure there are ENT tests, but I think this is fine to merge here and merge up to ENT for formal tests

**Comment by mnesbit** [comment]
We should ensure there are ENT tests, but I think this is fine to merge here and merge up to ENT for formal tests

**Comment by rick-r3** [comment]
I was just trying to understand what scenarios does this fix?

**Comment by nikinagy** [comment]
If we are in a different time zone for example in BST (or switch the computer to another time zone) and start a flow in a node, the corresponding database entries (e.g. entries in vault_states) are going to be inserted with UTC timestamp to the database.

**Review by rick-r3 — APPROVED** [review]

**Review by mnesbit — APPROVED** [review]
OK

**Pull request merged**
