### PR TITLE
[ENT-5210] - Whitelist SNAPPY encoding

### PR DESCRIPTION
**Pull request by dimosr**
Whitelist SNAPPY encoding and move some of the serialization functionality in the internals.

### CODE REVIEW

**Review by rick-r3 — APPROVED** [review]
LGTM

**Comment by rick-r3** [comment]
I somehow converted this from a draft - don't know how to convert it back!  The label on the button was misleading!  Happy for it to be merged.

**Comment by rick-r3** [comment]
Oh, I've found the secret "convert to draft" option up under the reviewers section.  Anyway, I think it's potentially ready to merge, isn't it ?

**Comment by dimosr** [comment]
yes, I think we can merge. It will make things a lot easier, since otherwise I would have to build an open-core artifact from this branch to build on top for the rest.

**Pull request merged**
