### PR TITLE
Remove .idea folder and add to .gitignore

### PR DESCRIPTION
**Pull request by stevenroose**
IDE-specific files don't belong in a source tree.

Since I use IntelliJ IDEA myself, the existence of the `.idea/` folder does not allow me to add the code as a module in my project.

### CODE REVIEW

**Comment by mikehearn** [comment]
Hiya,

The run configs are there deliberately and referred to from the documentation, they simplify setup.

If you use "open" and then use the gradle import bubble, rather than the "import" option on the splash screen, then IntelliJ will notice the .idea directory already exists and do the right thing automatically. It shouldn't be causing any problems, or at least, doesn't on 2016.3 - the only thing that can go wrong is if you pick "import" from the welcome splash then IntelliJ will erase the .idea directory and recreate it, which means you lose the run configs. It's discussed a bit here:

https://docs.corda.net/getting-set-up-fault-finding.html

**Comment by stevenroose** [comment]
So Corda only has IDEA-specific run configurations provided?

You're forcing developers into a very tight setup... What if I don't want to "open" Corda as a pre-build project, but want to add it as a module to my existing project. 

I believe it might be a better idea to just provide the run configurations separately for users to install when they want instead of keeping them hidden in the `.idea/` folder and forcing users to setup their IDE exactly like you do in order to be able to use the run configurations.

**Comment by ragmondo** [comment]
Hi Steven - so far yes just IntelliJ run configs have been provided and the purist me agrees that IDE configurations shouldn't normally live with the source code for exactly the reasons you specify. However.. we are trying to make the introduction at this stage as frictionless as possible - and that's why we've included them for now. We do actually have quite frequent conversations about exactly how to structure the repo (and if it should be multiple repos etc etc) and I'll keep you point in mind the next time we do discuss this.

**Comment by mikehearn** [comment]
For adding it as a dependency to an existing project we've published Maven artifacts, so it should be usable as with any other library. Is the issue here that you're only using the IntelliJ build system and not in combination with Maven/Gradle?

If you want to import it as an IDEA submodule into an existing project then yeah, we haven't really thought about that setup. As Rich says, we will discuss it a bit more.

That said, including a .idea with at least some things in isn't that uncommon and JetBrains support it, that's what the "Share" option in the run config screen is for. If you look at the Kotlin repository then it has a .idea directory too:

https://github.com/JetBrains/kotlin/tree/master/.idea

Some of the stuff in this directory is intended to be personal and user-specific, but other stuff is project related. So I don't think we're doing anything all that weird.

**Pull request closed without merging**
