### PR TITLE
Merging cid 878 non party flow sessions into master

### PR DESCRIPTION
**Pull request by roger-that-dev**
Merging in this work as it was missed before.

### CODE REVIEW

**Comment by gendal** [comment]
"as it was missed before" << any more info on this?  This is a pretty sizeable piece of work. Do we know there are no other pieces of work that could be 'missed'? Do we know what happened?

**Comment by roger3cev** [comment]
The feature branch was merged before Will merged his work into the feature branch.

**Comment by roger3cev** [comment]
This PR can be closed now as the work was merged into the 4.3 release branch.

**Comment by gendal** [comment]
ok - great. thanks.

**Pull request closed without merging**
