### PR TITLE
Revert Tweak JUnit 5 configurations to keep vintage engine off compile classpaths.

### PR DESCRIPTION
**Pull request by josecoll**
This reverts commit b9f7c1a which caused an increase in Unit test executions times of 15-30 minutes.
https://github.com/corda/corda/pull/5138

Identified as part of investigations into test execution performance degradation on:
[**EXPERIMENTAL: Investigating poor test execution performance**](https://github.com/corda/corda/pull/5156)

Unit test execution times drop back to sub 45 mins:
https://ci-master.corda.r3cev.com/viewLog.html?buildId=176553&buildTypeId=Corda_PullRequests&tab=buildResultsDiv

### CODE REVIEW

**Comment by josecoll** [comment]
This revert is to get our CI pipeline back into a non-timeout working order.
Follow-up work would need to determine how we tackle this properly.

**Comment by chrisr3** [comment]
@josecoll If you're going to restore `useJUnitPlatform()` then please just **close** this PR instead because it now contains _nothing_ worth putting back into Corda.

**Comment by chrisr3** [comment]
See #5164 - the slowdown can be fixed by reverting `useJUnitPlatform()` _only_. We want to keep everything else.

**Comment by josecoll** [comment]
Superseded by https://github.com/corda/corda/pull/5173

**Pull request closed without merging**
