### PR TITLE
Adds overload anotations and reorganizes param orders to improve java…

### PR DESCRIPTION
**Pull request by joeldudleyr3**
… interop.

### CODE REVIEW

**Comment by joeldudleyr3** [comment]
Sure - which part?

**Comment by exFalso** [comment]
Could do something simple akin to DriverTests.kt, just so we have some java code to poke the api.

For the flow api it'd be more involved, but i reckon if there's an upcoming java project that's good enough

**Comment by joeldudleyr3** [comment]
I've added the tests. In a few cases, I've wrapped the calls in a lambda, which has the advantage of allowing the test to check that the right type of params are passed in, while not actually calling the function, so the params themselves can be junk.

**Comment by joeldudleyr3** [comment]
I've reverted the tests - let's take that up as a separate thing.

**Pull request merged**
