### PR TITLE
NOTICK Merge OS 4.6 -> OS 4.7 20200922

### PR DESCRIPTION
**Pull request by fowlerrr**
Merge

### CODE REVIEW

**Comment by rekalov** [comment]
is this for OS->ENT 4.6 or OS 4.6->4.7?

**Comment by fowlerrr** [comment]
> is this for OS->ENT 4.6 or OS 4.6->4.7?

🤦‍♂️ OS 4.6 -> OS 4.7 

Ignore the dodgy branch name...

**Comment by fowlerrr** [comment]
Also, note that it's currently broken.  That is being currently looked at as the merge was less than pleasant.

**Review by bpaunescu — DISMISSED** [review]
My changes look good

**Review by lankydan — APPROVED** [review]

**Review by rekalov — APPROVED** [review]

**Review by wzur-r3 — APPROVED** [review]
My files looks good
* `.ci/dev/compatibility/JenkinsfileJDK11Azul`

**Review by vkolomeyko — APPROVED** [review]

**Review by blsemo — APPROVED** [review]
My changes look fine

**Pull request merged**
