### PR TITLE
Class and interface serialisation blacklisting

### PR DESCRIPTION
**Pull request by kchalkias**
CordaClassResolver now requires both a white and a blacklist.
Some key concepts:
- Blacklisting is always checked before whitelisting
- {White,Black}-listing inheritance is now allowed. We should consider however a model where you can define, using a second param, if inheritance is permitted.
- There are two global transient lists (one for white, one for black).
- Exception is always descriptive (if in whitelist or blacklist)

What is left:
1. List of known blacklisted classes/interfaces (will do/decide in an upcoming PR)
2. different lists for p2p and storage Kryo
3. links to wiki when throwing (it would help if we had error codes)
4. Having discuss it with Rick, we must consider if we should remove annotations and keep white/blacklisting only, because dealing with both ways will get much more complex to handle (inheritance, global/per app, p2p vs storage... etc).

### CODE REVIEW

**Comment by mikehearn** [comment]
I am not at all convinced by this. Why did it get so complicated? This could have just been a big if or when statement in the Kryo used for checkpointing. This change adds more public API and changes security sensitive code in big ways. Moreover it seems strange - having both whitelist AND blacklists doesn't make sense, that's redundant. Why would you blacklist something whitelisted?

The reason I suggested we need a blacklist is because the Kryo checkpointer allows you to serialise anything, it's not using the annotation based whitelisting, so what I meant was something specific to that.

The actual list is the important thing here.

**Comment by kchalkias** [comment]
The main reason is it can be applied in the future for security purposes as well and it can also serve our checkpoint requirements.
Developers can whitelist classes, but we should not allow some specific classes, even if they do (so these classes should be defined in a blacklist, right?
Also by having a blacklist, you can better inform users on serialisation errors (it's either blacklisted or they forgot to whitelist)

**Comment by kchalkias** [comment]
As for the public api, I guess this can be easily fixed by having a constructor with a default blacklist, so it remains backwards compatible.
Regarding the list of classes, my intention was to first agree on the model, cause if for example we allow inheritance a couple of things should change. However it's not that easy, for instance I guess we would like to blacklist autocloaseables, but we now enable streams. Also, if you blacklist a hashset (inherently) you automatically blacklist linkedhashset.

**Comment by kchalkias** [comment]
I find no reason why this model doesn't serve the checkpoint purpose as well. I understand it adds some complexity, but this is required if it is to be reused in the future for security checks and to my taste it is reusable, safer and possibly more scalable.
But in any case (even if I eventually require to totally refactor it), we should decide on how we handle inheritance before starting adding blacklisted classes to the set.

**Comment by mikehearn** [comment]
OK - @rick-r3 can you review this please?

**Comment by kchalkias** [comment]
I am closing this, as after multiple discussions, we decided on a simpler model based on whitelists. See [828](https://github.com/corda/corda/pull/828). This however will server as a basis if in the future we'll decide to use both whitelists and blacklists in `CordaClassResolver`.

**Pull request closed without merging**
