### PR TITLE
Cleaned up DistributedNotaryTests, including renaming it

### PR DESCRIPTION
**Pull request by shamsasari**
I'm changing the node config slightly in my host verification work and this test needed updating. It made more sense to fix up the test and use existing mechanisms to start nodes than to apply a (temporary) patch.

There's also some overlap with another test class and so I've renamed both to more accurately describe their purpose's.

### CODE REVIEW

**Comment by adagys** [comment]
maybe it's worth just merging those two tests?

**Comment by shamsasari** [comment]
The intent of the other test, as far as I understand, is testing Artemis' ability to handle distributed services, which is why I've added a TODO for one of the tests to be moved.

**Comment by adagys** [comment]
true, but it's still quite coupled with the raft notary, and I feel like it would be simpler to have them all in one place. To test only Artemis' ability to handle distributed services, it'd be best to have some dummy distributed service (as currently we might get unrelated notary failures) but seems like too much of a hassle at this point.

**Comment by shamsasari** [comment]
I can add a TODO to use a dummy distributed service.

**Comment by shamsasari** [comment]
TODO added, back to you.

**Pull request merged**
