### PR TITLE
[NOTICK] - Bump platform version to 7

### PR DESCRIPTION
**Pull request by dimosr**
Bumping platform version to 7 for 4.5

### CODE REVIEW

**Comment by rick-r3** [comment]
Required by sendAll API change.

**Comment by rick-r3** [comment]
@dimosr Can you tickle the build and see if we can get it green?

**Review by rick-r3 — DISMISSED** [review]

**Comment by dimosr** [comment]
A link to the `sendAll` PR for future reference: https://github.com/corda/corda/pull/5990

**Comment by rick-r3** [comment]
@dimosr Tests seem to have a spurious failure that needs a re-run.

**Comment by dimosr** [comment]
re-triggered it, I think Jenkins is also having some issues atm that are being investigated by infra.

**Comment by dimosr** [comment]
@rick-r3 this is green now, should we merge it?

**Review by rick-r3 — APPROVED** [review]

**Pull request merged**
