### PR TITLE
CORDA-2743 - utilities and test to show rpc operations that support d…

### PR DESCRIPTION
**Pull request by tudor-malene**
first part of : https://github.com/corda/corda/pull/4933
That will go into CE4 and 4.1

### CODE REVIEW

**Comment by shamsasari** [comment]
This needs backporting to OS 4.1 and ENT 4.0.

**Comment by gendal** [comment]
nice!  we should make a song and dance about this once it's available... we presumably want as many users as possible to use this or something like it i assume?  (let's make sure we include something in changelog and release notes so the release process picks it up)

**Comment by tudor-malene** [comment]
Thanks @gendal ,
This is pretty much the  best we can do with what is available at the moment.

People who need this sort of resilience (everyone?) must keep it in mind when writing flows ( add some discriminator to the state or some other non visible internal state) and also add the check in the flow if they want to be 100% it's not triggered twice.

Umm, I'm thinking now that we could create a sample CorDapp that contains that Flow-level logic to give people the complete solution.
The CorDapp could create an internal table: `FlowDeduplicationTable (pk: uuid)`, and a  generic subflow `DeduplicationFlow` which is called first thing and saves the uuid passed in from rpc. If the flow was already triggered this step fails with a ConstraintViolation so the flow can only run once.
Also some flow could return if the uuid was inserted to act as a generic logical retry.

**Comment by gendal** [comment]
interesting....  is this something that we'd need long term or does it just paper over the cracks of the rpc implementation (metaphor?)

**Comment by shamsasari** [comment]
The question is how much more effort do we want to put into this knowing that we should have a better solution in Corda 5. If that release is some time away then it might be worth it.

**Comment by tudor-malene** [comment]
The cracks are pretty wide...
I wonder if the product team is actually aware of these limitations. Maybe we should get them involved.

Long term we definitely need this sort of functionality. The questions are how and when it gets implemented and when clients can switch to that version.

**Comment by gendal** [comment]
cc @joeldudleyr3

**Pull request merged**
