### PR TITLE
Add legacy version of BFT notary service tests

### PR DESCRIPTION
**Pull request by rnicoll**
Add legacy version of BFT notary service tests as a stand-in for currently broken tests.

### CODE REVIEW

**Comment by rnicoll** [comment]
Hopefully this is stabler on CI, as we've had these in for a while, just ensuring we don't accidentally end up with breaking changes committed because tests are missing.

**Comment by andr3ej** [comment]
I'm going to re-enable the BFT tests once their failure rate is low enough. Why the urgency?

**Comment by rnicoll** [comment]
Happened to be on the review for a PR that would have broken BFT, and while I spotted it by hand in this case, it was pure luck that I was the reviewer for that PR. Essentially we risk reversions being committed without these tests functioning.

**Comment by andr3ej** [comment]
Was it ServiceIdentityGenerator, and don't the Raft tests cover that case?

**Comment by josecoll** [comment]
@adagys probably better suited to review / approve this than me.

**Comment by rnicoll** [comment]
I think this is now redundant as the new tests have been re-enabled, meant to close this earlier, doing so now.

**Pull request closed without merging**
