### PR TITLE
ENT-1249 - Downgrade Artemis from v2.4 to v2.1

### PR DESCRIPTION
**Pull request by tlil**
Downgrade Artemis to version 2.1 to protect against rogue non-TLS connections causing OOM.
 * https://issues.apache.org/jira/browse/ARTEMIS-1559

mem-leak
mem-leak-source

### CODE REVIEW

**Comment by mikehearn** [comment]
Is this bug reported to upstream anywhere? We need a fix in 2.4 - if we downgrade we'll lose large message streaming support again.

**Comment by tlil** [comment]
@mikehearn Yes, I'm currently trying to find out if it is reported or not. If it isn't, I'll raise an issue with upstream.

I've been talking to @cburlinchon and @mnesbit. The thinking is that it would be a temporary downgrade for code freeze tomorrow. Next, we would obviously need to get the issue resolved with Artemis v2.4 as part of the large message work. Sucks, but would rather not expose vulnerabilities like this in the pre-release we cut tomorrow

**Comment by tlil** [comment]
@mikehearn: **If we were to roll back**: Given the number of changes in 2.2.0 ([changelog](https://activemq.apache.org/artemis/release-notes-2.2.0.html)), would you prefer rolling back to what we were using prior to 2.4.0, which was 2.1.0?

**Comment by mikehearn** [comment]
OK then. Can you put a comment in the Gradle file explaining why we're on such an old version of the broker? And ideally with a link to the upstream bug report?

**Comment by tlil** [comment]
Absolutely - will put that in. Any preference as to what version? 2.2.0 is the latest version where this leak doesn't trigger an OOM. However, we were on version 2.1.0 prior to the 2.4.0 bump.

**Comment by mikehearn** [comment]
Let's go back to 2.1.0 for now to keep things simple and go back to 2.4 ASAP.

**Comment by tlil** [comment]
Coolie, will update accordingly. Ta

**Comment by tlil** [comment]
@mikehearn @cburlinchon updated with description

**Comment by jbertram** [comment]
It would be awesome to get a reproduce for this on the upstream ARTEMIS JIRA.  Is this feasible?

**Comment by tlil** [comment]
Hi @jbertram – yeah, sorry, I've been out. Hopefully back next week, so I'll jump on this then. ([ARTEMIS-1559](https://issues.apache.org/jira/browse/ARTEMIS-1559?focusedCommentId=16303612&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16303612)

**Pull request merged**
