### PR TITLE
In docs:key-concepts, transactions should come before contracts

### PR DESCRIPTION
**Pull request by siyopao**
👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

I am reading through the key-concepts in V3.3 of your docs [here](https://docs.corda.net/key-concepts.html) and I think that transactions should appear before contracts. Especially since the video for transactions is labeled Key Concepts 3 and the video for contracts as Key Concepts 4.

“I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).”

# PR Checklist:

- [x] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [x] If you added public APIs, did you write the JavaDocs?
- [x] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [x] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Thanks for your code, it's appreciated! :)

### CODE REVIEW

**Comment by joeldudleyr3** [comment]
Thanks, good catch.

**Comment by joeldudleyr3** [comment]
@siyopao Can I add you to the contributors list? https://github.com/corda/corda/blob/master/CONTRIBUTORS.md. Let me know how to list you if so (it's generally "NAME <COMPANY>").

**Comment by siyopao** [comment]
@joeldudleyr3 Hi. I am honoured to be added, but I really didn't contribute much. I guess "Craig Pastro" is the best way to list me. Thank you!

**Comment by joeldudleyr3** [comment]
Done :) Thanks!

**Comment by siyopao** [comment]
@joeldudleyr3 Cool! Thanks!

**Pull request merged**
