### PR TITLE
INFRA-456 Add codeowners

### PR DESCRIPTION
**Pull request by rnicoll**
Add initial codeowners for OS. I've tried to resolve any conflicts sensibly, but please let me know if there's any mistakes/missed entries.

I do want to introduce new teams for code ownership later, but for now wanted to get something in place sooner rather than later.

### CODE REVIEW

**Review by chrisr3 — DISMISSED** [review]
Yikes.

**Comment by rick-r3** [comment]
@rnicoll Can a super user override ?  Just thinking during the period we have individuals and not teams as owners, we could see an issue with a code owner on PTO.  As long as there's a "break glass" procedure in the short term just in case, we can handle it. Probably cover that in any process documentation we do associated with this.

**Comment by rnicoll** [comment]
@rick-r3 You can definitely turn off the protections for a branch, at least. I presume regular admin overrides work the same way they work for bypassing required checks, too.

**Review by vkolomeyko — DISMISSED** [review]

**Comment by rekalov** [comment]
I can also take `node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice`

**Comment by rnicoll** [comment]
@rekalov Ah I'd missed `crypto` and `cryptoservice` were individual entries, fixed.

**Review by dimosr — APPROVED** [review]

**Review by rekalov — APPROVED** [review]

**Review by rick-r3 — APPROVED** [review]
Shall we merge and see what happens?

I guess merges will become a bit of an approva-thon.

**Comment by rnicoll** [comment]
@rick-r3 It will just auto-add owners initially, enforcement is a separate option I'll turn on later.

**Pull request merged**
