### PR TITLE
Split users for bank and big corp

### PR DESCRIPTION
**Pull request by rnicoll**
Minor tweak to users as a precursor to #196

### CODE REVIEW

**Comment by josecoll** [comment]
@rnicoll You want approval to to merge this into your other branch right?

**Comment by gendal** [comment]
Make sure this is REALLY LOUDLY communicated when it's merged. A lot of people use the explorer to show demos... changing the userids and passwords is the kind of thing that seems minor but REALLY messes people up... especially when they're on a deadline trying to get a client demo ready, etc.      One answer might be just to check with Chris that whatever he's building for the demo bench has auto-login, etc., so it's a nonissue for those scenarios.

**Comment by mikehearn** [comment]
DemoBench has autologin for the Explorer and database viewer already.

**Comment by rnicoll** [comment]
This is the only place I can see that we've split the two roles, so far. I'd suggest if we're doing it across the codebase, it needs a JIRA item to track the work required.

**Comment by josecoll** [comment]
@rnicoll let it to me, I'll raise a separate PR and align the credentials.

**Pull request merged**
