### PR TITLE
BREAK RPC API!!!! Muhahaha!!!!

### PR DESCRIPTION
**Pull request by chrisr3**
This BAD CHANGE should fail the "API Change Gate" on TeamCity.

### CODE REVIEW

**Comment by Clintonio** [comment]
It failed to fail.

**Comment by Clintonio** [comment]
Ah yes - please rebase. I need to add a fail on error condition.

**Comment by mnesbit** [comment]
Will it catch parameter signature changes?

**Comment by chrisr3** [comment]
Yes, it does.

**Pull request closed without merging**
