### PR TITLE
CORDA-499: Restructure TransactionGraphSearch to be Dokka-friendly

### PR DESCRIPTION
**Pull request by rnicoll**
* Remove internal state of TransactionGraphSearch from being publicly visible.
* Add Dokka comments for TransactionGraphSearch.Query values.
* Move query into TransactionGraphSearch constructor as it should always be set except for test cases.

### CODE REVIEW

**Comment by mikehearn** [comment]
It's good, but actually I wonder if we can just move this class to be internal. Where is it used? Such graph searches won't be possible after SGX anyway.

**Comment by rnicoll** [comment]
It's only used in the trader demo, to find the original issuance state for logging. Won't this remain valid to use from flows, just not from contracts?

It perhaps should be a vault query, though, especially as I think it implies a linearity between states which is not necessarily true.

**Comment by mikehearn** [comment]
Let's move it into the trader demo then. I think it's only used to fish out a document attached to the initial issuance, right? That can be addressed in an SGX compatible way by propagating the attachment through every transaction.

**Comment by rnicoll** [comment]
Ready for re-review

**Comment by rnicoll** [comment]
Can I have a review on this please?

**Pull request merged**
