### PR TITLE
DemoBench now subscribes to updates for transaction and vault RPCs.

### PR DESCRIPTION
**Pull request by chrisr3**
Properly subscribe to the RPC Observables rather than polling the transactions and the vault.

### CODE REVIEW

**Comment by mikehearn** [comment]
Can you introduce and document a utility val in the client:jfx module (will need to add a direct dependency on RxJava) for an RxJava JavaFX scheduler? It can be something ultra-simple, like:

`val JavaFXThread: Scheduler = Schedulers.from(Executor { Platform.runLater(it) })`

Then instead of using Platform.runLater directly everywhere, you can do something like:

`observable.subscribeOn(JavaFXThread) { ... /* on ui thread already */ }`

**Comment by chrisr3** [comment]
Interesting idea, but JavaFX doesn't seem to like it:
```

**Comment by chrisr3** [comment]
Interesting idea, but JavaFX doesn't seem to like it:
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-0 (ActiveMQ-client-global-threads-1685635915)
```
It looks as if
```kotlin
val JavaFXThread: Scheduler = Schedulers.from({ Platform.runLater(it) })
```
does not cause the subscriber to run on the FX application thread. It just expects to be invoked there.

**Comment by mikehearn** [comment]
Ah ha. RxJavaFX has one, and yeah, it's apparently more complicated than that.

We could copy this class into client:jfx, and convert it to Kotlin? Depending on all of RxJavaFX for this seems a bit overkill and I'm not sure the rest is all that necessary.

https://github.com/ReactiveX/RxJavaFX/blob/2.x/src/main/java/io/reactivex/rxjavafx/schedulers/JavaFxScheduler.java

**Comment by chrisr3** [comment]
Hmm, speaking of "overkill", could we do this as a separate PR?

**Comment by chrisr3** [comment]
I'm hardly an Rx expert, but [this blog](http://tomstechnicalblog.blogspot.co.uk/2016/02/rxjava-understanding-observeon-and.html) makes interesting reading. I think it's saying that you can't blithely use `observeOn()` and expect it to work. In our case, we need to be _sure_ that the UI thread can keep up with the RPC thread, or else the `observeOn()` ring-buffer will overflow. I think we're OK here, it's a local solution rather than a generic one.

**Comment by mikehearn** [comment]
Yes, sure, of course. If updates come in too fast for the UI thread to keep up then you'd want to use one of the Rx sampling or buffering operators.

**Comment by chrisr3** [comment]
I'm still not understanding why `subscribeOn(fxScheduler).subscribe { ... }` _doesn't_ run my subscription operation on the JavaFX thread though. Oh well.

**Pull request merged**
