### PR TITLE
NOTICK - Python script for creating test tickets in JIRA

### PR DESCRIPTION
**Pull request by tlil**
Python script for creating 'Platform Test' and 'Platform Test Run' instances in JIRA for use in release testing.

### CODE REVIEW

**Comment by GavT** [comment]
Is there a user guide / readme for this which describe how to use the switches at the command line?

**Comment by tlil** [comment]
I was gonna add that plus some other options next week. Didn't have time before I took off yesterday, @GavT

**Comment by fenryka** [comment]
Also, on error, it doesn't print help out which might be useful :)

**Comment by fenryka** [comment]
Additionally. Some of the error checking, like correct version strings, could be done by the library automagically

**Comment by fenryka** [comment]
Small change to get this working with NS and without linking template to epics, can be changed of course but this got things working for 0.2

**Comment by tlil** [comment]
Ta, yep, I had a few more changes that I wanted to make anyway. Just didn't have time before heading out on Thursday. Will do that today.

**Comment by tlil** [comment]
@fenryka @GavT I've updated the script a little to copy across "blocks"-links from the template, allowing for backfilling of test cases and test run tickets, etc.

I'll write up some docs etc. as well. So still considered WIP.

**Comment by tlil** [comment]
Added doc: [README.md](https://github.com/corda/corda/blob/0dabacd48109a1379daafd1b026795388098edf2/release-tools/testing/README.md)

**Pull request merged**
