### PR TITLE
TM-204 Fixing regression builds

### PR DESCRIPTION
**Pull request by Schife**
Regression builds started failing due to io.spring.dependency-management being removed from maven central. Removing it and supplying spring versions

### CODE REVIEW

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Comment by Schife** [comment]
run tests: pr-merge

**Review by chrisr3 — DISMISSED** [review]
LGTM; it's the latest version.

**Comment by Schife** [comment]
run tests: smoke

**Review by chrisr3 — DISMISSED** [review]
Sweet! LGTM :grinning:

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: smoke

**Comment by Schife** [comment]
run tests: slow

**Comment by Schife** [comment]
run tests: smoke

**Review by chrisr3 — APPROVED** [review]
LGTM - I'll assume it behaves on Jenkins now.

**Pull request merged**
