### PR TITLE
OS 4.4 release notes: added warning about integration testing changes

### PR DESCRIPTION
**Pull request by VCAMP**
Added release notes to reflect changes introduced in https://github.com/corda/corda/pull/6014

### CODE REVIEW

**Review by chrisr3 — COMMENTED** [review]
Look OK; can we assume that developers know about adding CorDapps to out-of-process nodes explicitly via `DriverParameters`? (Linked to relevant part of docs?)

**Comment by VCAMP** [comment]
> Look OK; can we assume that developers know about adding CorDapps to out-of-process nodes explicitly via `DriverParameters`? (Linked to relevant part of docs?)

I linked the only part of the docs I could find that seemed relevant (https://docs.corda.net/tutorial-integration-testing.html?highlight=driver%20dsl) - not sure if there's a more appropriate page?

**Comment by chrisr3** [comment]
I have an 11th Hour, 59th Minute addition to this PR. The `corda-node-driver` will now _also_ exclude any JAR that has the `Corda-Testing` attribute in its MANIFEST.MF. The following artifacts have been correspondingly updated with this `Corda-Testing` attriibute:
- `corda-node-driver`
- `corda-test-utils`
- `corda-test-common`
- `corda-test-db`
- `corda-mock`

**Comment by VCAMP** [comment]
> * `corda-test-common`
> * `corda-test-db`
> * `corda-mock`

@chrisr3 have added the required changes - apologies for the delay (your reply got lost in a bunch of other Github notifications). Can you approve if all looks fine?

**Review by chrisr3 — APPROVED** [review]
LGTM

**Pull request merged**
