### PR TITLE
ENT-1633 increase node max heap size to 512m

### PR DESCRIPTION
**Pull request by tudor-malene**
ref: https://r3-cev.atlassian.net/browse/ENT-1633

Increase to 512m from 200m

### CODE REVIEW

**Comment by josecoll** [comment]
@rick-r3 are you happy with this minimum footprint change?

**Comment by rick-r3** [comment]
The 200MB limit was to make it possible to run networks on folks laptops.  Does the OOM happen with open source as well as enterprise?  I can see a higher requirement for enterprise being easily acceptable.  If OS is also needing more, I wonder if we can figure out how to reel in the demands on netty.

**Comment by tudor-malene** [comment]
I've checked the memory usage on both OS and ENT, and it is very close to 200m.
I can easily see how it can randomly go over.
Maybe we can set the Xms to 200m, and the jvm will go up to 512m when required.

**Comment by rick-r3** [comment]
I seem to remember we held the footprint where it was so @gendal and others could run some of the demos (DemoBench presumably) on their laptops.  Richard, what was the spec of those laptops and are we intending to maintain this ?  We're going to have to raise the limit anyway unless we spend ages working out how/if to control the memory consumption of things like Artemis.

5 nodes at a max of 512MB is "only" 2.5GB, plus DemoBench itself.

**Comment by gendal** [comment]
I hadn't realised the 200MB limit was to appease me!!  I did once try to get Corda running on a 512MB ancient Raspberry Pi, and it would be a shame to lose that (silly) proof point.  But, aside from that, the only requirement is, I guess, the one you outline:  we do need to be able to demo Corda on laptops...    The CorDapp Example spins up four nodes plus web servers IIRC and DemoBench often needs four nodes for meaningful demos.  But 4x500MB plus web servers plus DemoBench overhead is still comfortably within 4GB, right?

**Comment by gendal** [comment]
(That said...  why is a node doing nothing getting so big?  Is it also a sign we need to focus on bloat during a cleanup period?)

**Comment by rick-r3** [comment]
Sounds like we should be okay with this increase just to keep things going.  It would be good to spend some clean up time understanding how to control the memory footprint.  My profiling in the perf cluster seems to indicate Artemis/netty grabs 512MB eventually, and that is the bit we don't currently understand how to influence / reduce.  That feels worse than it was originally but that's anecdotal.  There may be some other uses we can reduce to help small demo setups (I was just checking that Artemis/netty didn't appear to have a leak under load in the perf cluster, and it indeed seemed to stabilise and stop growing).

**Pull request merged**
