### PR TITLE
DEVOPS-764 - Jolokia dependency is incorrectly specified and removed in master

### PR DESCRIPTION
**Pull request by Clintonio**
This is a backport of 5d91531ee09c29584092c963eb3e05d65b55d77a

### CODE REVIEW

**Comment by Clintonio** [comment]
Just realised I need to backport a couple of other fixes with it - will do tomorrow

**Comment by fenryka** [comment]
I completely missed this @Clintonio why are we removing things, not saying it's wrong, I just need some context

**Comment by Clintonio** [comment]
@fenryka https://r3-cev.atlassian.net/browse/CORDA-1636

The solution turned out to be that we already removed it in master, so I'm backporting this fix. It fixes Maven projects depending on Corda. I am not the original reporter nor the original person who removed the code in master. This backport, if not important, could be ignored. I am not sure how badly it impacts maven builds, but I suspect it blocks them entirely.

**Comment by fenryka** [comment]
Thanks for the update, I'll merge, just wondered what it was for :)

**Pull request merged**
