### PR TITLE
Adel/merge from 4.5

### PR DESCRIPTION
**Pull request by adelel1**
Merge from OS 4.5

### CODE REVIEW

**Review by JamesHR3 — APPROVED** [review]
My changes look good.

**Review by fowlerrr — APPROVED** [review]
My change looks good

**Review by rekalov — APPROVED** [review]

**Review by lankydan — APPROVED** [review]

**Review by wzur-r3 — APPROVED** [review]
Jenkinsfile for regression build looks good.

**Review by jakubbielawa — APPROVED** [review]

**Review by mnesbit — APPROVED** [review]
OK

**Pull request merged**
