### PR TITLE
Failover-less reapObservables for prompt shutdown

### PR DESCRIPTION
**Pull request by andr3ej**

### CODE REVIEW

**Comment by mikehearn** [comment]
Does this resolve the hang when a node quits in DemoBench? (issue #1041 )

**Comment by exFalso** [comment]
This means that after failover we won't reap anymore as the reaper session closes. So we need a different approach. What causes the delay with the current code?

**Comment by andr3ej** [comment]
@mikehearn I don't know - I found this problem while trying to clean up initial RPC connection failure more robustly, as part of ongoing work to make tests not interfere with each other.
@exFalso I didn't see that, as the exception was being dropped. So I've added logging, and changed it so that the pool doesn't recycle closed producers. IIRC reapObservables was getting stuck in ChannelImpl:256 about half the time at the end of BootTests.`node quits on failure to register with network map`, if you change driver to wait until the executor actually terminates. It may be possible to achieve the same result by cancelling reaperScheduledFuture with interrupt, but this way is more robust (no risk of 3rd party code swallowing the interrupt) and cleaner.

**Comment by exFalso** [comment]
@mikehearn It's the same issue, but in a different codepath (during shutdown the artemis session close is trying to wait for failover - but the other side is already gone)

**Comment by andr3ej** [comment]
Steps to reproduce "hang that isn't currently in master":
1. Add some printlns around it.producer.send(message) in reapObservables
2. Run BootTests.`node quits on failure to register with network map` in a loop

You'll see it frequently takes 30 seconds longer than it should. This PR fixes that.

**Comment by exFalso** [comment]
I cannot reproduce this hang (I ran >100 tests consecutively), but from what I understand it's the same issue as #689 
We could raise an issue with Apache, but I'm not sure whether they will provide a fix for this, as this only happens when the broker shutdown happens at the same time client shutdown does.
This PR basically changes reapObservables to use a custom "failover" using the pool. I don't think this is the right approach, it complicates the code in a non-trivial and implicit way.
We could do a similar hack for now as we did with demobench - just insert a sleep between the shutting down of the broker and the clients.

**Comment by andr3ej** [comment]
Not everyone has to be able to reproduce it for it to be a bug:
proof

**Comment by andr3ej** [comment]
What this PR actually does is change reapObservables back to how it was before failover was blanket enabled for everything the rpc object does. There is no failover-via-pool, an equivalent naive implementation would be to use a fresh session/producer for each firing of reapObservables, all the pool does is recycle the ones that don't fail. Whether or not this is the right approach, adding a sleep certainly is not!

**Comment by exFalso** [comment]
Right, creating a fresh session per reapObservables and buffering in between is what I call custom failover. This is not what it was doing before, it used to simply fail when it was sending.

Neither this PR nor the sleeping is the right solution, both are workarounds for a limitation(bug?) in Artemis. But if we had to pick a workaround it should be the less invasive one, which is the sleep.

Alternatively we can dive into Artemis code and see whether we can somehow signal that the shutdown shouldn't wait for a reply from the broker, this would be the cleanest

**Comment by andr3ej** [comment]
>it used to simply fail when it was sending.

on any error, silently stopping the reapObservables task for the remaining lifetime of the proxy, which is a bug

>if we had to pick a workaround it should be the less invasive one, which is the sleep.

no we pick the reliable one, which is never a sleep

>Alternatively we can dive into Artemis code and see whether we can somehow signal that the shutdown shouldn't wait for a reply from the broker, this would be the cleanest

perfect is the enemy of good

**Comment by exFalso** [comment]
You're right, it shouldn't be silent when it fails - can you raise a separate PR for this please?

**Comment by andr3ej** [comment]
Closing for remix

**Pull request closed without merging**
