### PR TITLE
Upgrade Kotlin to 1.2.20

### PR DESCRIPTION
**Pull request by mikehearn**
I did that thing I'm good for these days ;)

### CODE REVIEW

**Comment by mikehearn** [comment]
This is hitting some issue where the kryo serialiser isn't doing the right thing for singletons anymore.

**Comment by shamsasari** [comment]
I get a similar error on master in Intellij. Making `TestSingleton` public makes the problem go away.

The `targetType.kotlin.objectInstance` call in `CordaClassResolver#registerImplicit` is throwing an `IllegalAccessException`:
```
Class kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2 can not access a member of class net.corda.nodeapi.internal.serialization.KryoTests$TestSingleton with modifiers "public static final"
```

I wonder where the regression occurred as on 1.1.60.

**Comment by mikehearn** [comment]
The problem is a JVM access check. The reflection library used to be able to reflect over `private object Foo` and determine it was a singleton. It's no longer possible to do that, I'm not sure why but presumably some small semantic change in Kotlin reflection. So it throws an exception which is then swallowed and ignored as "not an object" even though it is, resulting in the test failure. Making the object not private is a simple fix, but there may be other cases like this. Will investigate a bit further.

**Comment by shamsasari** [comment]
Yes that's what I concluded. My hunch is that they removed the `setAccessible` call in `KClassImpl$Data$objectInstance$2`.

**Comment by shamsasari** [comment]
The code has no `setAccessible`:
https://github.com/JetBrains/kotlin/blob/b5fa520aa507cb6fbbfc5f6c78752ecb9c7786a5/core/reflection.jvm/src/kotlin/reflect/jvm/internal/KClassImpl.kt#L104
But looking through history this is old code and hasn't been touched recently so I don't think it's ever had `setAccessible`.

**Comment by mikehearn** [comment]
I debugged it a bit yesterday. I think the test has always been flaky and the Kotlin upgrade just revealed it. The question is how did it ever pass - Kryo *is* handing back the exact same object instance when using CompatibleFieldSerializer, but it's unclear how it does that or why. I wasn't able to debug very successfully because I couldn't reproduce the passing case inside IntelliJ and I didn't want to make a custom build of Kryo with print statements in just to satisfy my curiousity.

Anyway this commit fixes it: https://github.com/corda/corda/commit/38ccd0572c3ff186a039631b84df54dcf2e54e6d

**Comment by mikehearn** [comment]
@shamsasari @Clintonio Can you review this please? It got a bit involved along the way.

**Comment by shamsasari** [comment]
I've already approved. The button is green!

**Comment by mikehearn** [comment]
Yeah, but it changed quite a bit since then. Can I get a review of the new changes?

**Comment by shamsasari** [comment]
I already did.

**Comment by mikehearn** [comment]
Ah, great. Thanks.

**Pull request merged**
