### PR TITLE
CORDA-3356 Subflow ledger consistency tests + move statemachine tests to slow integration tests

### PR DESCRIPTION
**Pull request by lankydan**
Add tests for subflows that fail during transitions.

Split out `StatemachineErrorHandlingTest` into a series of smaller tests.

Move these tests into the `integration-test-slow` category so they are
not run against every PR.

### CODE REVIEW

**Comment by lankydan** [comment]
run smoke tests

**Comment by roastario** [comment]
run smoke tests

**Comment by lankydan** [comment]
run smoke tests

**Review by mnesbit — APPROVED** [review]
OK

**Comment by lankydan** [comment]
run smoke tests

**Pull request merged**
