### PR TITLE
Added intro white paper spanish translation

### PR DESCRIPTION
**Pull request by davidleeuk**
Please review

### CODE REVIEW

**Comment by josecoll** [comment]
The translation as it stands is not suitable for publication.
I have annotated my PDF printed copy with all the mistakes and errors, but to summarise:
- repeated usage of specific words which are incorrect (eg. _partes_ is used everywhere to denote _participants_ but translates literally to _parts_; _exigible_ is another example) or incomplete (eg. _efectivo_ is used for cash but should really be _dinero efectivo_, _clausulado_ should be _clausulado legal_)
- translation of certain words that are either out of context or not commonly used in the Spanish language (eg. fehaciente, asuncion, subyace)
- literal translations of technology terms and phrases which are really meaningless as literal translations (eg. it would be better to keep the English term and reference a glossary to explain the term): _clausulado_, _contrato inteligente_, BFT)
- similarly, usage of an English term (eg. sandbox) within a Spanish sentence without any explanation to what this means (should be a reference to a glossary to explain)
- page 7 has a strange misprint of a word (bullet point 2)
- page 8 Capitalization missing on 4th bullet point
- page 3 Full stop missing in 2nd _Contexto_ section paragraph
- 3.1 Poor section title translation
- incorrect grammar in certain paragraphs (p10 bullet point 2)
- p13 last sentence - should be _estados compartidos_ (eg. shared states)
- p14 _inputs_  y _outputs_ should be _entradas y salidas_
- p15 _codigo wallet_ should be _codigo de cartera_
- p15 _ensamblaje_ should be _lenguaje ensamblador_
- p15 last bullet point: _oscurecer_ (darken) should be _ocultar_ (hide)
- p16 5th bullet point is incorrectly phrased
- p16 9th bullet point should refer to a "_cartera de inversiones_" (or _portafolio_)
Conclusion has both a grammatical error and uses the word _exigir_ and _exigible_ in wrong context

**Comment by davidleeuk** [comment]
Thanks - @josecoll to apply updates in tex file

**Comment by mikehearn** [comment]
I'm going to close this for now. Once it's been fixed Jose can just commit it directly, unless we have another Spanish speaker who can review Jose's review.

**Comment by josecoll** [comment]
well - as per the email discussion yesterday regarding the differences between LATAM Spanish and (Castilian) Spanish.
If we are going with Carlos Arena's (LATAM) translation of the Corda.net site, then he should also review and edit this Introductory White Paper to reflect the same LATAM vocabulary.

**Comment by davidleeuk** [comment]
@josecoll following discussion - please can you go ahead and make the amendments you see fit to the .tex file, and rebuild. Once you've made the changes you feel able to make, I'll then pass to Carlos for LATAMisation. 

I agree a glossary would be useful - have asked people to fill in https://r3-cev.atlassian.net/wiki/display/AR/Technical+dictionary so I can pass it back to translators for future reference. To make this work you would need to write Spanish prose definitions of each term which is just left in the English. That said, I wonder if this isn't overkill - presumably if a reader encounters a foreign term they don't understand, they can google until they find the meaning?

**Comment by mikehearn** [comment]
I'm going to close this again. Please don't leave PRs open when they aren't being worked on. If this needs prioritisation then let's coordinate with Gavin to ensure whoever needs to be working on this does so.

**Pull request closed without merging**
