### PR TITLE
CORDA-3021: Introduce `SignOnlyCryptoService` and use it whenever possible

### PR DESCRIPTION
**Pull request by vkolomeyko**
Re-worked my earlier changes after discussion with @fowlerrr and @dimosr

### CODE REVIEW

**Comment by vkolomeyko** [comment]
> This seems like an unnecessary refactoring, and likely to cause more confusion that clarification.

@josecoll - thanks for your feedback.
I wonder if you were able to check the underlying Jira for the purpose of the change: https://r3-cev.atlassian.net/browse/CORDA-3021 ?
Appreciate that in Corda OS the benefit may not be immediately obvious, but there are many more `CryptoService`s in ENT and creating SignOnly version of `CryptoService` will be a lot more natural for Corda Firewall.

**Comment by josecoll** [comment]
> > This seems like an unnecessary refactoring, and likely to cause more confusion that clarification.
> 
> @josecoll - thanks for your feedback.
> I wonder if you were able to check the underlying Jira for the purpose of the change: https://r3-cev.atlassian.net/browse/CORDA-3021 ?
> Appreciate that in Corda OS the benefit may not be immediately obvious, but there are many more `CryptoService`s in ENT and creating SignOnly version of `CryptoService` will be a lot more natural for Corda Firewall.

If the underlying reason for this refactor is to align the smaller API surface with its many different implementations in the Firewall, why not just encapsulate this `SignOnlyCryptoService` within the ENT-only `bridge/firewall` module itself ?

**Comment by vkolomeyko** [comment]
@josecoll 
In CordaFirewall we were originally using our own factory for `CryptoService`s, but given that people adding new HSM vendors it became out-of-date. So we decided to switch to the "official" one from `nodeapi` module.
Of course we can create facade and wrap fully powered `CryptoService` inside `SignOnlyCryptoService` in CordaFirewall, but this is again sub-optimal as creating fully powered `CryptoService` is a lot more involved than `SignOnlyCryptoService` in the first place.
I propose to park this conversation for now. Later this week @fowlerrr and I agreed to talk and align refactoring we are independently doing in `CryptoService`.
Please let me know if you want to be involved in this white-boarding session and I will invite you in.

**Comment by josecoll** [comment]
OK - probably best to label this PR with "Work in Progress" then until you decide on the correct approach going forward.

**Comment by vkolomeyko** [comment]
> What about adding some unit tests that now also create a sign only crypto service. Other than this looks fine to me.

**Comment by vkolomeyko** [comment]
@fowlerrr - thanks for your input and approval.
@dimosr, @josecoll, @adelel1 - you previously have seen this code. Could you have a quick second look and let me know if you are happy for these changes to be merged?

**Pull request merged**
