### PR TITLE
Reduce logging of registration of custom serializers by making loggin…

### PR DESCRIPTION
**Pull request by shamsasari**
…g of core types debug level

### CODE REVIEW

**Comment by fenryka** [comment]
What is our obsession with not logging things that may actually be usful to people and anyone looking at a log file wondering what may have been going on? I've already argued this with @vkolomeyko  

If we want the tests to run faster make changes that reduce logging for the tests, but I think having which serializers are loaded into a factory recorded is useful

Debug level = might as well not bother since any time you look at a log file it will be gone

**Comment by vkolomeyko** [comment]
But @fenryka - I think during our conversation consensus been reached? (and PR: corda/corda#3633 is approved and merged)

**Comment by shamsasari** [comment]
I understand the rationale for info logging when it's registering custom serializers for CorDapp specific classes. I can't see how it helps a CorDapp developer to know that a custom serializer has been registered for `java.math.BigInteger` or `java.time.LocalTime`. The work "custom" is actually misleading - there is no customisation going on here for these classes; it's using the same hardocded serialisers. So distract the dev's attention with this info?

**Comment by shamsasari** [comment]
I could change it so that the debug logging is more specific to classes in `DefaultWhitelist`.

**Comment by shamsasari** [comment]
I'm not sure what changes #3633 made, but the node things on each start up, and it's the *same* classes each time:

```
[INFO ] 2018-07-19T14:12:20,189Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="interface java.security.PublicKey" {}
[INFO ] 2018-07-19T14:12:20,192Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="interface java.security.PrivateKey" {}
[INFO ] 2018-07-19T14:12:20,213Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.Throwable" {}
[INFO ] 2018-07-19T14:12:20,214Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.StackTraceElement" {}
[INFO ] 2018-07-19T14:12:20,219Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.math.BigDecimal" {}
[INFO ] 2018-07-19T14:12:20,221Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.math.BigInteger" {}
[INFO ] 2018-07-19T14:12:20,223Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.Currency" {}
[INFO ] 2018-07-19T14:12:20,225Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class net.corda.core.utilities.OpaqueBytesSubSequence" {}
[INFO ] 2018-07-19T14:12:20,228Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Instant" {}
[INFO ] 2018-07-19T14:12:20,231Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Duration" {}
[INFO ] 2018-07-19T14:12:20,234Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDate" {}
[INFO ] 2018-07-19T14:12:20,241Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDateTime" {}
[INFO ] 2018-07-19T14:12:20,242Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDate" {}
[INFO ] 2018-07-19T14:12:20,242Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalTime" {}
[INFO ] 2018-07-19T14:12:20,242Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalTime" {}
[INFO ] 2018-07-19T14:12:20,250Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZonedDateTime" {}
[INFO ] 2018-07-19T14:12:20,250Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDateTime" {}
[INFO ] 2018-07-19T14:12:20,251Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,251Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,256Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.OffsetTime" {}
[INFO ] 2018-07-19T14:12:20,256Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalTime" {}
[INFO ] 2018-07-19T14:12:20,256Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,263Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.OffsetDateTime" {}
[INFO ] 2018-07-19T14:12:20,264Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDateTime" {}
[INFO ] 2018-07-19T14:12:20,264Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,267Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.Optional" {}
[INFO ] 2018-07-19T14:12:20,271Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Year" {}
[INFO ] 2018-07-19T14:12:20,274Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.YearMonth" {}
[INFO ] 2018-07-19T14:12:20,276Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.MonthDay" {}
[INFO ] 2018-07-19T14:12:20,280Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Period" {}
[INFO ] 2018-07-19T14:12:20,283Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.Class" {}
[INFO ] 2018-07-19T14:12:20,286Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.security.cert.X509Certificate" {}
[INFO ] 2018-07-19T14:12:20,289Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.security.cert.X509CRL" {}
[INFO ] 2018-07-19T14:12:20,292Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.security.cert.CertPath" {}
[INFO ] 2018-07-19T14:12:20,293Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.StringBuffer" {}
[INFO ] 2018-07-19T14:12:20,295Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.io.InputStream" {}
[INFO ] 2018-07-19T14:12:20,298Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.BitSet" {}
[INFO ] 2018-07-19T14:12:20,302Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.EnumSet" {}
[INFO ] 2018-07-19T14:12:20,302Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.Class" {}
[INFO ] 2018-07-19T14:12:20,310Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class net.corda.core.contracts.ContractAttachment" {}
[INFO ] 2018-07-19T14:12:20,312Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class org.apache.activemq.artemis.api.core.SimpleString" {}
[INFO ] 2018-07-19T14:12:20,827Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="interface java.security.PublicKey" {}
[INFO ] 2018-07-19T14:12:20,827Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="interface java.security.PrivateKey" {}
[INFO ] 2018-07-19T14:12:20,829Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.Throwable" {}
[INFO ] 2018-07-19T14:12:20,830Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.StackTraceElement" {}
[INFO ] 2018-07-19T14:12:20,830Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.math.BigDecimal" {}
[INFO ] 2018-07-19T14:12:20,830Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.math.BigInteger" {}
[INFO ] 2018-07-19T14:12:20,830Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.Currency" {}
[INFO ] 2018-07-19T14:12:20,831Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class net.corda.core.utilities.OpaqueBytesSubSequence" {}
[INFO ] 2018-07-19T14:12:20,831Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Instant" {}
[INFO ] 2018-07-19T14:12:20,831Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Duration" {}
[INFO ] 2018-07-19T14:12:20,831Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDate" {}
[INFO ] 2018-07-19T14:12:20,832Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDateTime" {}
[INFO ] 2018-07-19T14:12:20,832Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDate" {}
[INFO ] 2018-07-19T14:12:20,832Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalTime" {}
[INFO ] 2018-07-19T14:12:20,832Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalTime" {}
[INFO ] 2018-07-19T14:12:20,833Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZonedDateTime" {}
[INFO ] 2018-07-19T14:12:20,833Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDateTime" {}
[INFO ] 2018-07-19T14:12:20,833Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,833Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,834Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.OffsetTime" {}
[INFO ] 2018-07-19T14:12:20,834Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalTime" {}
[INFO ] 2018-07-19T14:12:20,834Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,835Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.OffsetDateTime" {}
[INFO ] 2018-07-19T14:12:20,835Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.LocalDateTime" {}
[INFO ] 2018-07-19T14:12:20,835Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.ZoneId" {}
[INFO ] 2018-07-19T14:12:20,836Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.Optional" {}
[INFO ] 2018-07-19T14:12:20,836Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Year" {}
[INFO ] 2018-07-19T14:12:20,836Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.YearMonth" {}
[INFO ] 2018-07-19T14:12:20,836Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.MonthDay" {}
[INFO ] 2018-07-19T14:12:20,837Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.time.Period" {}
[INFO ] 2018-07-19T14:12:20,837Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.Class" {}
[INFO ] 2018-07-19T14:12:20,837Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.security.cert.X509Certificate" {}
[INFO ] 2018-07-19T14:12:20,838Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.security.cert.X509CRL" {}
[INFO ] 2018-07-19T14:12:20,838Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.security.cert.CertPath" {}
[INFO ] 2018-07-19T14:12:20,843Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.StringBuffer" {}
[INFO ] 2018-07-19T14:12:20,843Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.io.InputStream" {}
[INFO ] 2018-07-19T14:12:20,843Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.BitSet" {}
[INFO ] 2018-07-19T14:12:20,844Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.util.EnumSet" {}
[INFO ] 2018-07-19T14:12:20,844Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class java.lang.Class" {}
[INFO ] 2018-07-19T14:12:20,844Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class net.corda.core.contracts.ContractAttachment" {}
[INFO ] 2018-07-19T14:12:20,844Z [main] amqp.SerializerFactory.register - action="Registering custom serializer", class="class org.apache.activemq.artemis.api.core.SimpleString" {}
```

**Comment by fenryka** [comment]
We don't need to repeat it more than once per class, but telling them what is and isn't covered is useful, and its useful for devs if someone ever wants to see whats loaded vs what an error message is saying

**Comment by fenryka** [comment]
Given that nodes should be long-lived, it only looks like spam in a test environment... and I'm mostly concerned with prod

**Comment by shamsasari** [comment]
OK

**Pull request closed without merging**
