### PR TITLE
CORDA-3795 Revert H2 version to .197

### PR DESCRIPTION
**Pull request by fowlerrr**
Revert the version as .199 has a bug in it.

### CODE REVIEW

**Comment by rick-r3** [comment]
I think this is a tricky one.  I get why we would want to do this, to align with Enterprise, but I think as far as we can tell, 197 has this disk space leak that results in large database files.  It seems to be fixed beyond 197 although no clear confirmation.  This disk space leak is fine for Enterprise because H2 is definitely not supported there outside of tests.

**Comment by mnesbit** [comment]
Why are we doing this here? Surely this is just for a customer specific CE patch not a general rollback to a broken version

**Comment by mnesbit** [comment]
Also, we have long had -DexcludeJar:  commandline arg to drop one of our internal classpath items and jarDirs to add an alternate search source. Is that not a better approach to this?

**Comment by fowlerrr** [comment]
This was just me being consistent.  But I can see the argument for _not_ doing it here so I'll close this one.

**Pull request closed without merging**
