### PR TITLE
Added H2 port to cordformation config

### PR DESCRIPTION
**Pull request by Clintonio**
Why: It's useful to have deterministic ports.

### CODE REVIEW

**Comment by mnesbit** [comment]
Should this include a tag for the Crash Shell port too?

**Comment by mnesbit** [comment]
Actually, can we make the camel case consistent with the other properties?

**Comment by Clintonio** [comment]
@mnesbit Can do.

**Comment by Clintonio** [comment]
I will be changing it in Cordformation but don't want to break the config with this PR.

**Comment by Clintonio** [comment]
@mnesbit Back in your court.

**Pull request merged**
