### PR TITLE
Typos and optimised imports

### PR DESCRIPTION
**Pull request by cioro**
- Fixed typo in KotlinUtils.kt
- Optimised imports in trader demo

### CODE REVIEW

**Comment by mikehearn** [comment]
Hey Rocio :) Can you please state that you've read and agreed to the contributor agreement (the PR description would have had a link to it).

@shamsasari please don't approve PRs but then leave them unmerged!

**Comment by shamsasari** [comment]
We currently can't merge into master due 1.0.

**Comment by mikehearn** [comment]
Ah, right.

**Comment by mikehearn** [comment]
Shams, this PR was never merged - I'll take over and make sure it gets in. Sorry Rocio!

**Comment by cioro** [comment]
Thanks Mike!

**Comment by mikehearn** [comment]
Merged - I don't think typo fixes and import optimisations are actually copyrightable (not sufficiently creative works) but it'd be nice if you could say you're authorised to contribute anyway, in case there's a next time! Please accept my apologies for us taking so long about this.

**Pull request merged**
