### PR TITLE
Fix circular dependency between the 2 vault objects

### PR DESCRIPTION
**Pull request by andr3ej**
It's obfuscated by ServiceHub, but VaultService was calling into VaultQueryService.

### CODE REVIEW

**Comment by josecoll** [comment]
If anything, we collapse the two services into one.
What do you think @rick-r3 ?

**Comment by josecoll** [comment]
Sorry but I find this refactoring totally unnecessary and confusing.
Why are you even making these changes to existing working code? (who requested this work?)

**Comment by andr3ej** [comment]
I've reimplemented so that the API stays the same, and so that the 2 objects no longer communicate with each other via ServiceHub, which is related to a big refactor of AbstractNode startup.

**Comment by josecoll** [comment]
We should not be performing major refactoring of any critical code (eg. AbstractNode) at this stage.
Again, where is the JIRA story that specifies the need for this work?

**Pull request closed without merging**
