### PR TITLE
INFRA-242 New stage that checks git commit messages

### PR DESCRIPTION
**Pull request by Schife**
New Jenkinsfile stage that checks commit messages are in the proper format and if not sends an email to the author informing him of the correct format

### CODE REVIEW

**Comment by mnesbit** [comment]
This work doesn't follow its own recommendation! I think this will be counter productive

**Comment by Schife** [comment]
Indeed those were test commits to test out the implementation and check if an email would be sent but some issues have been discovered. Mainly around getting an accurate changeset between build in jenkins as well as getting a change set on the first build of a PR

**Comment by mnesbit** [comment]
Has this plan been communicated ahead of time to the team? Presumably this only applies to the squashed commits onto release branches? What are implications for feature branches?

**Comment by Schife** [comment]
Please squash when merging

**Comment by Schife** [comment]
New solution has been implemented to check PR titles instead

**Pull request closed without merging**
