### PR TITLE
Move flows into net.corda.core.node.flows package

### PR DESCRIPTION
**Pull request by rnicoll**
Move flows into net.corda.core.node.flows package to structurally match services in net.corda.core.node.services package, and to separate implemented flows from the classes flows are based on.

Part of https://r3-cev.atlassian.net/browse/CORDA-499

### CODE REVIEW

**Comment by rnicoll** [comment]
`net.corda.core.node.flows` may not be the correct destination, but really think we should keep implementations separate from the infrastructure code that they're based on.

**Comment by rnicoll** [comment]
The other option might be a new `net.corda.flows` package, which would look a little out of place in the `core` module, but fits naming elsewhere. Trying to move these into the `node` module hits problems with the build dependencies (finance doesn't depend on node, so won't compile without these flows in core)

**Comment by rick-r3** [comment]
I think we largely leave the flows and the annotations where they are (it's easy to visually see which are annotations as IDEs render them differently in the sidebar).  But we could move:

`AbstractStateReplacementFlow.kt`
`FlowException.kt`
`FlowLogic.kt`
`FlowLogicRef.kt`
`FlowStackSnapshot.kt`
`StateMachineRunId`

into a sub-package of `net.corda.core.flows` (e.g. `net.corda.core.flows.types`)

**Comment by rick-r3** [comment]
BTW, IntelliJ has fully qualified lots of classes.  Watch out for that.... it seems to like doing it when moving things around.

**Comment by rnicoll** [comment]
Raised #1356, which moves the API into a new package, for comparison. However it touches more code and generally I'm not sure it's the better option.

**Comment by rick-r3** [comment]
Let's close this too

**Pull request closed without merging**
