### PR TITLE
Refactor :client module into :client:javafx and :client:mock

### PR DESCRIPTION
**Pull request by chrisr3**
At the moment we have `:client` and `:client:jackson` modules. However, `:client:jackson` does not depend on `:client` and so this module structure is unclear. Hence we migrate the classes from `:client` into `:client:javafx` and `:client:mock`.

My intention here is to create a logical place to put a new `:client:rpc` module.

### CODE REVIEW

**Comment by exFalso** [comment]
Exactly my thoughts wrt `client` vs `client:jackson`. I think we should have a clearly defined way of organising modules. We should be able to justify:
* **What a module encapsulates and why**. I think the most straight-forward way of checking this would be to examine top-level dependencies of the module, and compare them with the use cases of the module. For example the `rpc` module will depend on artemis, which is justified, as all users of rpc will need to communicate with the node. A negative example would be `core` depending on h2. Users of `core` include node clients, which shouldn't need to pull in database dependencies.
* **If it's a submodule, why it's a submodule**. First off I'd say the way you split up `javafx` and `mock` is the way to go. Submodules' parents should not contain functionality but rather should just group submodules. For each submodule-group we should be able to say why a new module should or shouldn't be in it. I think we can say this for `samples` and `tools`, but I don't think we can for `node` or `client`.

In any event I think this is a right step forward.

**Comment by chrisr3** [comment]
Matthew has requested that the `.fx.` package be renamed to `.jfx.` to avoid confusion with "exchange rate".

**Comment by Clintonio** [comment]
My only concern is with naming a module after another product (JavaFX) that is a trademark. Otherwise it looks good. Either rename the module or just double check internally as to whether it's acceptable to publish a binary called "javafx.<version>.jar". My understanding of trademark law is weak but the little I do know makes me concerned enough to want to check first.

**Comment by mikehearn** [comment]
Lots of libs do that sort of thing, or call themselves e.g. ControlsFX. It's not legally a problem because there's no realistic possibility of it being confused with the actual javafx (as opposed to something that uses javafx) or any intent that it might.

**Comment by chrisr3** [comment]
I've just sent an email to Isabelle Corbett upstairs...

**Pull request merged**
