### PR TITLE
Added Chinese version of intro white paper - please rebuild and commi…

### PR DESCRIPTION
**Pull request by davidleeuk**
Please rebuild and commit correct PDF (all characters readable) before approving

### CODE REVIEW

**Comment by mikehearn** [comment]
The PDF looks OK to me? What specifically is corrupt?

**Comment by patrickkuo** [comment]
Both PDF uploaded by @davidleeuk contains lot of replacement characters (�) I will regenerate Traditional Chinese version as well.

**Comment by mikehearn** [comment]
That's odd. I downloaded the PDF and I saw no replacement characters at all. What's going on here, I wonder? Default character set issues?

**Comment by patrickkuo** [comment]
hmm... weird, its not showing properly on my(OSX) and @davidleeuk's(Windows) machine, it looks fine after I changed the document class to '\documentclass[UTF8]{ctexart}'
There are some error in the latex log complaining about missing characters in font set when I run typeset, maybe its a font issue.

**Comment by mikehearn** [comment]
OK, well, good to fix it so it works everywhere.

**Comment by davidleeuk** [comment]
@patrickkuo If it looks fine to you then I'd argue we should merge as-is. Getting our other Chinese speaker(s) to sit down and proof-read it more extensively might take weeks and their feedback can be reflected in a later update - @mikehearn do you agree?

**Comment by mikehearn** [comment]
Agreed. Do we have any native speakers who can proofread for us?

**Comment by patrickkuo** [comment]
@mikehearn, Kenneth in Taiwan and the team in Singapore should be able to help.
@davidleeuk, agreed, I will approve the PR

**Comment by davidleeuk** [comment]
@Clintonio why did the TeamCity build fail? This is blocking the merge.

**Comment by mikehearn** [comment]
Flaky test, ignore it.

**Pull request merged**
