### PR TITLE
Patch DemoBench for JavaFX bugs when building installers.

### PR DESCRIPTION
**Pull request by chrisr3**
There is a JavaFX bug that is occasionally crashing DemoBench with a NPE. While the correct fix is ultimately to patch OpenJDK, we need DemoBench to work **now**. The broken class is `sun.swing.JLightweightFrame`, which lives in `rt.jar` and cannot be overridden and so we need to update `rt.jar` itself. Or more accurately, we need to update the copy of `rt.jar` that JavaPackager includes in the DemoBench installers.

This fixes issue #1049.

### CODE REVIEW

**Comment by gendal** [comment]
I have been using a patched pre-M14 DemoBench build, trying to recreate the conditions that led to the hang.  I think I succeeded this morning.  After switching between monitors and putting PowerPoint in and out of full-screen mode, etc., the following was printed to the DemoBench log:

```
2017-07-20T06:57:07,122Z [INFO ] RPCClient - Startup took 5 msec
2017-07-20T06:57:07,123Z [WARN ] NodeRPC - Node 'CN=Bank of Breakfast Tea,L=Liverpool,C=GB,E=corda@city.gb.example' not ready yet (Error: AMQ119007: Cannot connect to server(s). Tried with all available servers.)
2017-07-20T06:57:09,501Z [INFO ] RPCClient - Startup took 1382 msec
2017-07-20T06:57:10,821Z [INFO ] NodeTerminalView - Node 'CN=Bank of Breakfast Tea,L=Liverpool,C=GB,E=corda@city.gb.example' is now ready.
2017-07-20T06:58:01,241Z [WARN ] JLightweightFrame - BUGFIX - NPE avoided
```

DemoBench continued to work normally after this point.

So it does look like this patch has the desired effect.

**Comment by mikehearn** [comment]
Yow! Have we filed this report or sent a patch upstream?

**Comment by chrisr3** [comment]
I've raised [this issue](https://github.com/JetBrains/jdk8u_jdk/issues/6) in the JetBrains repo, but haven't heard anything back yet.

**Comment by mikehearn** [comment]
I would not expect them to reply any time soon. That repo is really just a courtesy to the community - they don't provide any formal support for Swing. The right place to report it is via the Java bug tracking system. We can do this and then follow up via email to inquire about whether a fix will be prioritised.

Can we take your fix and submit to JetBrains as a PR, as a first step to submitting it to Oracle?

**Comment by chrisr3** [comment]
OK, it's a trivial patch to one file so that's easy enough.

**Pull request merged**
