### PR TITLE
Various small fixes

### PR DESCRIPTION
**Pull request by mikehearn**
Each commit can be reviewed separately.

### CODE REVIEW

**Comment by rnicoll** [comment]
Do we definitely need to remove `SignedTransaction.id`? It was added as a sanity check due to inconsistent serialization/deserialization causing problems (hash set or hash map I believe being the underlying cause). It may need to be better marked as a safety feature, though, yes.

**Comment by mikehearn** [comment]
The combination of the serialisation and sandboxing work should resolve hashmap issues. However, having a transaction state its own hash redundantly really isn't great protocol design, I feel. Very easy to forget to do a consistency check somewhere and introduce a security hole.

**Comment by rnicoll** [comment]
I'd definitely want to see a replacement test somewhere, even if it's a debug option. Tracking down unstable serialization/deserialization bugs is a nightmare, because they don't manifest in any obvious sense (the IDs aren't consistent, which generally shows up somewhere in the vault, a long way away from the underlying problem). I know we lost about 2 developer days last time we saw such a bug, and I think there's been other incidents as well, because they're so hard to isolate.

How about `SignedTransaction` only exposes calculated ID, and uses the serialized ID only for checks, and we'll tackle a permanent fix in a separate PR? We should have some sort of command line option for "Run with extended tests" that does things like deserializing states right after they're serialized, and checks the IDs.

**Comment by rnicoll** [comment]
P.S. Apart from that, all looks good!

**Comment by mikehearn** [comment]
No, I don't want to build any further hacks into the protocol or node to handle this: it's past time we should be "done" with the core transaction formats, and we still have the summaries feature to add. Let's just configure Kryo to throw if it finds a HashMap instead of a LinkedHashMap anywhere. @rick-r3 ?

**Pull request merged**
