### PR TITLE
Cleaned up the trader, irs and simm demos so that things like the ...

### PR DESCRIPTION
**Pull request by shamsasari**
... driver are used in test so that the node module isn't a compile dependency

### CODE REVIEW

**Comment by mikehearn** [comment]
TeamCity can't build this.

**Comment by shamsasari** [comment]
Yes, I'm working on it. Intellij didn't complain about compile errors when I submitted.

**Comment by Clintonio** [comment]
This work blocks the fat cordapps work (since a compile dependency on test-utils introduces a _lot_ of bloat into the cordapp)

**Comment by shamsasari** [comment]
Both a) and b) have been addressed. This leaves the FiberBox and the file upload service unused. Perhaps they can be removed in a separate PR. Back to you @rick-r3.

**Pull request merged**
