### PR TITLE
CORDA-976 - V3.0 release version bump

### PR DESCRIPTION
**Pull request by fenryka**
This is the pre-release branch

### CODE REVIEW

**Comment by josecoll** [comment]
Are we not following the conventions set out by R3 Corda:

```
    // Our version: bump this on release.
    ext.corda_release_version = "R3.CORDA-3.0.0-DEV-PREVIEW-2"    // "CORDA-3.0.0-DEV-PREVIEW" (Open Source)
    ext.corda_release_distribution = "com.r3.corda"             // "net.corda" for Corda (Open Source)

```

I think @Clintonio was keen to have everything lowercased to follow Maven naming conventions.

**Comment by fenryka** [comment]
I was just doing what we've done fore versions 1&2 but can change if that's what we're doing now

**Comment by fenryka** [comment]
so
corda.3.0 
or
CORDA.3.0
given we won't release patches onto a Corda release, rather another version of the mainline we probably don't need 3.0.0 as we've not done it for V1.0 and V2.0

**Comment by josecoll** [comment]
So based on Clinton's feedback on the Slack channel, the naming should drop . and use lowercase, to become:

`ext.corda_release_version = "r3corda-3.0.0"    // "corda-3.0.0" (Open Source)`

**Comment by fenryka** [comment]
works for me, I'll update corda master as well to be corda-4-snapshot

**Comment by josecoll** [comment]
You make a valid point though as our documentation standards still refer to X.Y (major.minor) versioning:
https://r3-cev.atlassian.net/wiki/spaces/CCD/pages/130748982/Versioning+Branching+and+Upgrade+Policy

But how do we intend to apply patches/fixes then?

**Comment by fenryka** [comment]
I assume we won't to Corda, only to R3 Corda, in which case that should be Mmp ordering, really needs discussing 

I'm going to assume Corda (not R3 Corda) is just Mm and only R3 Corda gets Mmp

**Pull request merged**
