### PR TITLE
Kapt is no longer run automatically when build is run.

### PR DESCRIPTION
**Pull request by Clintonio**
This is to prevent the schema files being regenerated on each compile.

### CODE REVIEW

**Comment by mikehearn** [comment]
TeamCity doesn't like it but I'm not sure why - the files it's talking about are checked in now, right?

**Comment by Clintonio** [comment]
Added Jose to the review since it suddenly grew in size and purpose (checked with him in person and the additional files are meant to be checked in!)

**Comment by josecoll** [comment]
Reviewing now ...

**Comment by josecoll** [comment]
Steps taken to review:
1) Clone repo and build from scratch (`./gradlew install`): FAILS
2) Explicitly build generate the schema code using `kapt` plugin & then build
     `cd node-schemas; ../gradlew kapt`
      `cd ..; ./gradlew install`)
SUCCEEDS but you end up with a modified generated file:
`modified:   node-schemas/generated/source/kapt/main/net/corda/node/services/vault/schemas/Models.java`

**Comment by Clintonio** [comment]
Ready for re-review. Was a very minor fix.

**Comment by mikehearn** [comment]
Hah, it's conflicting on Models.java - needs a rebase. I'll take myself off this thread now ...

**Comment by Clintonio** [comment]
Rebased :)

**Comment by josecoll** [comment]
Re-tested step 1) above and works fine now.

However, this is not workable for ongoing development as changes/additions to schemas require re-running the Kapt process (manually is fine), and the generated code is duplicated in the default Kapt generated source directory. The consequence is you end up with **duplicate classes**:

```
Joses-MacBook-Pro:node-schemas josecoll$ ../gradlew buildKapt
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:core:compileKotlin UP-TO-DATE
:core:compileJava UP-TO-DATE
:core:copyMainKotlinClasses UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:node-schemas:kaptKotlin
/Users/josecoll/IdeaProjects/corda-clinton/node-schemas/build/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultTxnNoteEntity.java:22: error: duplicate class: net.corda.node.services.vault.schemas.VaultTxnNoteEntity
public class VaultTxnNoteEntity implements VaultSchema.VaultTxnNote, Persistable {
       ^
/Users/josecoll/IdeaProjects/corda-clinton/node-schemas/build/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultStatesEntity.java:24: error: duplicate class: net.corda.node.services.vault.schemas.VaultStatesEntity
public class VaultStatesEntity implements VaultSchema.VaultStates, Persistable {
       ^
/Users/josecoll/IdeaProjects/corda-clinton/node-schemas/build/generated/source/kapt/main/net/corda/node/services/persistence/schemas/AttachmentEntity.java:21: error: duplicate class: net.corda.node.services.persistence.schemas.AttachmentEntity
public class AttachmentEntity implements Attachment, Persistable {
       ^
/Users/josecoll/IdeaProjects/corda-clinton/node-schemas/build/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultCashBalancesEntity.java:22: error: duplicate class: net.corda.node.services.vault.schemas.VaultCashBalancesEntity
public class VaultCashBalancesEntity implements VaultSchema.VaultCashBalances, Persistable {
       ^
/Users/josecoll/IdeaProjects/corda-clinton/node-schemas/build/generated/source/kapt/main/net/corda/node/services/vault/schemas/Models.java:9: error: duplicate class: net.corda.node.services.vault.schemas.Models
public class Models {
       ^
/Users/josecoll/IdeaProjects/corda-clinton/node-schemas/build/generated/source/kapt/main/net/corda/node/services/persistence/schemas/Models.java:9: error: duplicate class: net.corda.node.services.persistence.schemas.Models
public class Models {
       ^
:node-schemas:buildKapt

```

The correct solution is to source-code control the generated files in the same directory as the default kapt output directory, OR change the default kapt output directory to point to the one you have defined (which is at the top level of the module).

**Comment by josecoll** [comment]
See https://blog.nishtahir.com/2016/06/25/how-to-get-idea-to-detect-kotlin-generated-sources-using-gradle/

**Comment by Clintonio** [comment]
@josecoll We can add IntelliJ support in another PR. 

Ready for re-review. I had to do a lot of gradle magic to get this working.

**Comment by josecoll** [comment]
Looks good!!!
Good effort on persevering ...

**Comment by josecoll** [comment]
Not sure why your TC build is failing now though :-(

**Comment by Clintonio** [comment]
Updated. Looks like the test build became unhappy. Please review the latest commit.

**Pull request merged**
