### PR TITLE
Moved PhysicalLocationStructures into internal package

### PR DESCRIPTION
**Pull request by shamsasari**

### CODE REVIEW

**Comment by mnesbit** [comment]
How is NodeInfo not also affected?

**Comment by mnesbit** [comment]
Ah ok that has gone from NodeInfo. Presumably looked up from certificate data. Does that mean this class can be moved elsewhere completely?

**Comment by shamsasari** [comment]
`NodeInfo.getWorldMapLocation` was only used by the explorer so it was moved there in a previous commit.

**Comment by shamsasari** [comment]
Which class?

**Comment by mnesbit** [comment]
Well kind of the whole world city database could be tossed over the wall into :finance, or node-api?

**Comment by shamsasari** [comment]
Moved to finance

**Pull request merged**
